const navToggle = document.querySelector("[data-nav-toggle]");
const navLinks = document.querySelector("[data-nav-links]");

if (navToggle && navLinks) {
  navToggle.addEventListener("click", () => {
    const isOpen = navLinks.classList.toggle("is-open");
    navToggle.setAttribute("aria-expanded", String(isOpen));
  });

  navLinks.querySelectorAll("a").forEach((link) => {
    link.addEventListener("click", () => {
      navLinks.classList.remove("is-open");
      navToggle.setAttribute("aria-expanded", "false");
    });
  });
}

const page = document.body.dataset.page;
if (page) {
  document.querySelectorAll("[data-page-link]").forEach((link) => {
    if (link.dataset.pageLink === page) {
      link.classList.add("is-active");
    }
  });
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.areas": "Areas We Cover",
    "nav.aboutMe": "About Me",
    "nav.services": "Services",
    "nav.prices": "Pricing",
    "nav.reviews": "Testimonials",
    "nav.faq": "FAQ",
    "nav.contact": "Contact Us",
    "nav.privacy": "Privacy Policy",
    "nav.terms": "Terms & Conditions",
    "nav.search": "Search website",
    "nav.call": "Call Now",
    "nav.whatsapp": "WhatsApp",
    "home.eyebrow": "Professional Home & Commercial Cleaning",
    "home.h1": "AGU Clean Services",
    "home.lead": "Newcastle, Gateshead, Chester-le-Street and Durham. Trusted home, rental and commercial cleaning with fast quotes and friendly service.",
    "home.cta1": "Get Free Quote",
    "home.cta2": "View Services",
    "home.point1": "✔ Regular & fortnightly home cleaning",
    "home.point2": "✔ Full property deep clean",
    "home.point3": "✔ Move-out ready, agent standard",
    "home.point4": "✔ Offices, shops, salons and Airbnb resets",
    "home.quick": "Quick contact",
    "home.quickText": "Free quotes are available by phone, WhatsApp or contact form.",
    "home.area1": "Main service area",
    "home.area2": "Local flexible bookings",
    "home.area3": "Domestic and tenancy jobs",
    "home.quote": "Free Quote",
    "home.quoteText": "Fast response on WhatsApp",
    "home.trust1h": "Reliable & trusted",
    "home.trust1p": "A service clients can feel confident booking",
    "home.trust2h": "Fully insured",
    "home.trust2p": "Public liability cover for added peace of mind",
    "home.trust3h": "Flexible hours",
    "home.trust3p": "Weekday, evening and tailored booking options",
    "home.trust4h": "Free quotes",
    "home.trust4p": "WhatsApp or phone quotes with no obligation",
    "home.servicesH": "Cleaning services built around real client needs",
    "home.servicesP": "Simple service categories, clear communication and flexible scheduling make the business easy to trust and easy to book.",
    "services.jumpLabel": "Jump to service:",
    "services.openPage": "Open service page",
    "services.requestQuote": "Request Quote",
    "services.openSection": "Go to service section",
    "svc.domestic.h": "Domestic cleaning",
    "svc.domestic.p": "Regular weekly or fortnightly home cleaning focused on comfort, consistency and day-to-day upkeep.",
    "svc.deep.h": "Deep cleaning",
    "svc.deep.p": "Detailed full-property cleans for kitchens, bathrooms and neglected areas that need a proper reset.",
    "svc.tenancy.h": "End of tenancy",
    "svc.tenancy.p": "Move-out cleaning prepared for lettings, property handovers and clients who need a stronger finish.",
    "svc.commercial.h": "Commercial cleaning",
    "svc.commercial.p": "Offices, salons, shops and small business spaces cleaned to stay tidy, professional and ready for clients.",
    "svc.airbnb.h": "Airbnb cleaning",
    "svc.airbnb.p": "Fast turnaround support for short-stay properties, including reset-ready presentation between guests.",
    "svc.venues.h": "After-hours venues",
    "svc.venues.p": "Cleaning support for clubs, pubs and hospitality spaces that need flexible timing outside normal hours.",
    "home.whyH": "Why clients choose AGU Clean Services",
    "home.whyP": "The business should feel calm, trustworthy and professional. That starts with clear pricing, responsive contact and a dependable standard of work.",
    "home.why1": "✔ Fully focused on practical, client-facing cleaning services",
    "home.why2": "✔ Suitable for homes, offices, tenancy and Airbnb work",
    "home.why3": "✔ Friendly communication without corporate tone",
    "home.why4": "✔ Strong fit for local recommendations and repeat bookings",
    "home.aboutEyebrow": "About Agnieszka",
    "home.aboutH": "Friendly service with a professional standard.",
    "home.aboutP": "AGU Clean Services is positioned as a reliable local business that values trust, punctuality and a clean finish clients can immediately feel.",
    "home.about1": "✔ Local service for Newcastle, Gateshead, Chester-le-Street and Durham",
    "home.about2": "✔ Clear communication by phone or WhatsApp",
    "home.about3": "✔ Flexible quotes based on property size and scope",
    "home.pricingH": "Simple and clear starting prices",
    "home.pricingP": "Visible starting rates help the website feel professional while still keeping quotes flexible for property size, condition and exact scope of work.",
    "price.regular.h": "Regular cleaning",
    "price.regular.p": "Weekly or fortnightly visits",
    "price.regular.d": "General home upkeep and routine cleaning.",
    "price.deep.h": "Deep cleaning",
    "price.deep.p": "Depends on property size",
    "price.deep.d": "Thorough reset for kitchens, bathrooms and full homes.",
    "price.tenancy.h": "End of tenancy",
    "price.tenancy.p": "Move-out focused finish",
    "price.tenancy.d": "Prepared for landlords, agents and property handover.",
    "price.commercial.h": "Commercial",
    "price.commercial.p": "Flexible scheduling available",
    "price.commercial.d": "Offices, salons, shops and small business spaces.",
    "home.reviewsH": "Trusted locally for reliable, friendly cleaning",
    "home.reviewsP": "Real client feedback helps new customers feel confident booking a cleaner they can trust.",
    "home.rev1": "Very professional and easy to arrange. The flat looked fresh, clean and ready straight away.",
    "home.rev2": "Reliable service and good communication. Exactly the type of cleaner you feel comfortable recommending.",
    "home.rev3": "Helpful for tenancy cleaning and completed everything to a strong standard with no fuss.",
    "home.ctaBandH": "Ready to book? Contact us today!",
    "home.ctaBandP": "Message on WhatsApp, call directly or use the quote form for a fast response.",
    "home.ctaBand1": "Go to Contact",
    "home.ctaBand2": "View Prices",
    "dashboard.panelH": "Operations Dashboard Snapshot",
    "dashboard.panelP": "A practical one-screen view showing service flow, enquiries and booking context for cleaner conversion.",
    "dashboard.panelPoint1": "✔ Live service snapshots and next action guidance",
    "dashboard.panelPoint2": "✔ Direct flow from service pages to quote requests",
    "dashboard.panelPoint3": "✔ Clean visual control for team confidence",
    "dashboard.panelVisualAlt": "Premium brand token board",
    "dashboard.panelVisualCaption": "Design token panel for a premium brand-aligned interface.",
    "dashboard.openPanel": "Open dashboard",
    "dashboard.manageServices": "View service pages",
    "dashboard.contactForm": "Go to contact form",
    "dashboard.contactPanelP": "The dashboard route keeps lead status and service context visible across the whole customer journey.",
    "dashboard.airbnbLink": "View Airbnb service",
    "dashboard.contactNow": "Need help? Contact",
    "dashboard.panelCaption": "Visual operations view for a more reliable service experience.",
    "dashboard.brandPanelP": "Brand consistency increases when every service step is connected to the operational dashboard and action path.",
    "footer.desc": "Reliable, professional and affordable cleaning services for homes and businesses across Gateshead and surrounding areas.",
    "footer.pages": "Main Menu",
    "footer.legal": "Legal",
    "footer.contact": "Contact",
    "footer.note": "© 2026 AGU Clean Services. All rights reserved.",
    "footer.trade": "AGU Clean Services is a trading name of Agnieszka Kalina vel Kalinowska.",
    "about.eyebrow": "About AGU Clean Services",
    "about.h1": "About AGU Clean Services",
    "about.lead": "Local, trusted and professional cleaning in Newcastle and beyond.",
    "about.sec1h": "Built around trust, consistency and clear communication",
    "about.sec1p": "The business plan is simple: people do not only buy cleaning. They buy peace of mind, reliability and a cleaner who does not let them down.",
    "about.list1": "✔ Local focus on Newcastle, Gateshead, Chester-le-Street and Durham",
    "about.list2": "✔ Premium presentation without cold corporate language",
    "about.list3": "✔ Clear service categories clients understand immediately",
    "about.list4": "✔ Good fit for repeat domestic clients and property contacts",
    "about.coreEye": "Core Positioning",
    "about.coreH": "Friendly professional business",
    "about.coreP": "The website, contact style and service structure are designed to look established, honest and approachable from the first visit.",
    "about.core1": "✔ Reliable and friendly service",
    "about.core2": "✔ Flexible booking and simple quoting",
    "about.core3": "✔ Strong visual brand for online ads and referrals",
    "about.oppH": "Best business opportunities",
    "about.oppP": "The strongest growth areas from the business plan are regular domestic work, end of tenancy cleaning, Airbnb resets and contact with local letting agents.",
    "about.card1h": "Repeat home clients",
    "about.card1p": "Weekly and fortnightly bookings help create consistent revenue and local word-of-mouth referrals.",
    "about.card2h": "Tenancy cleaning",
    "about.card2p": "Higher-value cleaning jobs with strong fit for agents, landlords and end-of-lease schedules.",
    "about.card3h": "Airbnb support",
    "about.card3p": "Short-stay property resets add flexibility and build useful relationships with hosts and managers.",
    "about.storyH": "A brand designed to feel calm, polished and genuinely dependable.",
    "about.storyP": "AGU Clean Services is built to feel established, local and dependable. The goal is a calm, approachable brand experience with reliable standards clients can trust every time.",
    "about.story1H": "Local and personal",
    "about.story1P": "The business is positioned for Newcastle, Gateshead, Chester-le-Street and Durham with a local identity that feels personal rather than corporate.",
    "about.story2H": "Professional standard",
    "about.story2P": "Clients still expect punctuality, polish, strong communication and an overall standard they can rely on every time.",
    "about.story3H": "Built for repeat trust",
    "about.story3P": "The aim is not just a one-off clean. It is repeat work, recommendations and a strong reputation built through consistency.",
    "about.clientsH": "Who the service is best suited for",
    "about.clientsP": "The business plan is strongest where there is clear, repeatable need: homes, rental property handovers, Airbnb hosting and smaller business premises.",
    "about.clients1": "✔ Busy households needing regular weekly or fortnightly support",
    "about.clients2": "✔ Tenants, landlords and letting agents preparing for handover",
    "about.clients3": "✔ Airbnb hosts needing quick resets between guest stays",
    "about.clients4": "✔ Offices, salons, shops and other small commercial spaces",
    "about.standardEye": "Service Standard",
    "about.standardH": "What clients should expect every time",
    "about.standardP": "A premium local cleaning brand grows through consistency. That means clear communication, respect for the property and a visible finished result every visit.",
    "about.standard1": "✔ Respect for the home, office or rental property",
    "about.standard2": "✔ Clear arrival expectations and straightforward contact",
    "about.standard3": "✔ Detail-focused cleaning with a noticeable final finish",
    "about.standard4": "✔ Flexible quotes based on size, condition and scope",
    "about.processH": "Simple process, clear communication, no unnecessary friction",
    "about.processP": "The best client experience should feel easy from first message to finished clean. That is part of what makes the business feel more professional and trustworthy.",
    "about.process1H": "1. Enquiry",
    "about.process1P": "The client sends a message by phone, WhatsApp or contact form with the property type, area and required service.",
    "about.process2H": "2. Quote",
    "about.process2P": "A clear quote is prepared based on property size, condition, frequency and the exact scope of work.",
    "about.process3H": "3. Cleaning Visit",
    "about.process3P": "The clean is completed with a respectful, careful approach and a finished result that feels fresh, polished and professionally handled.",
    "about.ctaH": "Want to see the service structure?",
    "about.ctaP": "Go to the services and prices pages for the final public-facing offer.",
    "aboutme.eyebrow": "Meet Agnieszka",
    "aboutme.h1": "Meet Agnieszka - Your Local Cleaning Professional",
    "aboutme.lead": "Agnieszka Kalina vel Kalinowska is the founder and owner of AGU Clean Services. With years of cleaning and client-service experience, she has built the business around reliability, quality and genuine care for every job.",
    "aboutme.workH": "My Work",
    "aboutme.workP": "I approach every project individually, taking time to understand each client's needs and tailoring the service so the final result matches their expectations.",
    "aboutme.workP2": "I focus on reliability, punctuality and high-quality service. I use proven products and safe cleaning methods that help keep spaces fresh and clean for longer.",
    "aboutme.expH": "Experience",
    "aboutme.expP": "Over the years, I have gained experience in both private homes and commercial environments. That experience has taught me the value of care, precision and responsibility in every stage of the job.",
    "aboutme.exp1": "Completing every stage of the job with care and precision",
    "aboutme.exp2": "Respecting each client's property and personal space",
    "aboutme.exp3": "Maintaining discretion and professionalism at all times",
    "aboutme.exp4": "Working efficiently, effectively and with full responsibility",
    "aboutme.trustH": "Reliability and Trust",
    "aboutme.trustP": "My clients value reliability, honesty, attention to detail and consistently high standards of service, combined with friendly communication and a professional approach.",
    "aboutme.trustP2": "Inviting someone into your home or business is an important decision. That is why I always work to make every professional relationship comfortable, transparent and built on mutual trust.",
    "aboutme.valuesH": "What Clients Value Most",
    "aboutme.values1": "Reliability and honesty",
    "aboutme.values2": "Attention to detail",
    "aboutme.values3": "Consistently high standards of service",
    "aboutme.values4": "Friendly communication and a professional approach",
    "aboutme.bandH": "AGU Clean Services",
    "aboutme.bandP": "Reliable Cleaning. Professional Results.",
    "aboutme.bandP2": "Home - Office - Commercial Cleaning",
    "aboutme.bandP3": "Serving Newcastle, Gateshead, Chester-le-Street and Durham.",
    "services.eyebrow": "Final Service List",
    "services.h1": "Clear services for homes, rentals and small businesses.",
    "services.lead": "The offer is structured to be easy to understand at a glance and strong enough for both private clients and property-related work.",
    "services.card1H": "Regular home cleaning",
    "services.card1P": "Weekly or fortnightly domestic cleaning for routine upkeep and a consistently fresh home.",
    "services.card2H": "Deep cleaning",
    "services.card2P": "Kitchen, bathroom and full-house detailed cleaning when a standard clean is not enough.",
    "services.card3H": "End of tenancy",
    "services.card3P": "Move-out cleaning for tenants, landlords and letting agents needing a stronger presentation standard.",
    "services.card4H": "Commercial cleaning",
    "services.card4P": "Offices, shops, salons and small premises with flexible schedules to suit the business.",
    "services.card5H": "Airbnb cleaning",
    "services.card5P": "Cleaning and reset-ready presentation between guests for short-term rental properties.",
    "services.detailH": "Detailed service pages in one clear structure",
    "services.detailP": "Each service below is written as its own offer block, so clients can quickly understand what is included, who it is best for and when to request that type of clean.",
    "services.domesticH": "Domestic Cleaning",
    "services.domesticP": "Regular domestic cleaning is ideal for clients who want a clean, comfortable home without the stress of managing everything themselves each week.",
    "services.domesticEye": "Best for",
    "services.domesticSub": "A consistently fresh and well-kept home",
    "services.domesticBody": "This service is designed for everyday upkeep, helping clients stay on top of cleanliness with a dependable recurring schedule and a polished result.",
    "services.domestic1": "✔ Weekly or fortnightly visits",
    "services.domestic2": "✔ Kitchens, bathrooms, dusting and floors",
    "services.domestic3": "✔ Best for busy households and repeat clients",
    "services.deepH": "Deep Cleaning",
    "services.deepP": "A more intensive service for properties that need a proper reset, stronger detail work and a visibly fresher finish throughout the home.",
    "services.deepEye": "Detailed clean",
    "services.deepSub": "When a standard clean is not enough",
    "services.deepBody": "Deep cleaning is suited to first visits, seasonal resets or properties that need more detailed attention in kitchens, bathrooms and neglected areas.",
    "services.deep1": "✔ Detailed attention to kitchens and bathrooms",
    "services.deep2": "✔ Suitable before events, after busy periods or first-time cleans",
    "services.deep3": "✔ Flexible scope depending on property size and condition",
    "services.tenancyH": "End of Tenancy Cleaning",
    "services.tenancyP": "This service is intended for move-out situations where a property needs to look clean, presentable and ready for handover to the next tenant, landlord or agent.",
    "services.tenancyEye": "Move-out clean",
    "services.tenancySub": "Prepared for property handover",
    "services.tenancyBody": "It is one of the most valuable services in the offer because it solves a clear need and suits both private clients and property contacts.",
    "services.tenancy1": "✔ Stronger presentation standard for handover",
    "services.tenancy2": "✔ Suitable for tenants, landlords and letting agencies",
    "services.tenancy3": "✔ Useful where a more thorough finish is required",
    "services.airbnbH": "Airbnb Cleaning",
    "services.airbnbP": "A practical short-stay property service for hosts who need reliable cleaning and a clean, welcoming setup between guests.",
    "services.airbnbEye": "Turnaround service",
    "services.airbnbSub": "Ready for the next guest",
    "services.airbnbBody": "Airbnb cleaning focuses on speed, consistency and presentation so short-stay properties stay reset-ready between bookings.",
    "services.airbnb1": "✔ Fast reset between guest stays",
    "services.airbnb2": "✔ Focus on presentation, cleanliness and consistency",
    "services.airbnb3": "✔ Ideal for hosts and property managers",
    "services.commercialH": "Commercial Cleaning",
    "services.commercialP": "Commercial cleaning is suited to offices, shops, salons and other smaller business spaces that need a clean, professional environment for staff and customers.",
    "services.commercialEye": "Business spaces",
    "services.commercialSub": "Clean, presentable and easy to maintain",
    "services.commercialBody": "This service helps local businesses maintain a more polished environment without needing a large corporate cleaning contract.",
    "services.commercial1": "✔ Offices, salons, shops and similar premises",
    "services.commercial2": "✔ Flexible scheduling around business hours",
    "services.commercial3": "✔ A reliable local option for regular upkeep",
    "services.secH": "How the service pages should feel",
    "services.secP": "This structure makes the brand look established: visible categories, practical wording and no unnecessary marketing filler.",
    "services.list1": "✔ Direct service naming",
    "services.list2": "✔ Short explanations with real use cases",
    "services.list3": "✔ Easy route from service to quote request",
    "services.flowEye": "Best conversion flow",
    "services.flowH": "Service page → price page → contact page",
    "services.flowP": "That flow suits both local domestic clients and agent or host enquiries looking for fast clarity.",
    "services.ctaH": "Need rates for one of these services?",
    "services.ctaP": "Go to the prices page for the public starting-price structure.",
    "prices.eyebrow": "Our Pricing",
    "prices.h1": "Simple starting prices with flexible quoting.",
    "prices.lead": "Public rates build trust quickly. Final quotes still depend on property size, condition, frequency and scope of work.",
    "prices.airbnbH": "Airbnb cleaning",
    "prices.airbnbP": "Starting from £45 depending on property size and turnover requirements.",
    "prices.freeH": "Free quotes available",
    "prices.freeP": "Clients can request pricing by call, WhatsApp or the contact form.",
    "prices.areaH": "Service area",
    "prices.areaP": "Newcastle, Gateshead, Chester-le-Street and Durham, with quotes adjusted to property and travel context.",
    "prices.ctaH": "Need an exact quote?",
    "prices.ctaP": "Tell us the property type, location and service needed, and we can provide a tailored price.",
    "prices.back": "Back to Services",
    "reviews.eyebrow": "Testimonials",
    "reviews.h1": "What clients say about AGU Clean Services",
    "reviews.lead": "Friendly, reliable service and strong results are the standards we want every booking to reflect.",
    "reviews.formH": "Share your testimonial",
    "reviews.formP": "Tell us what worked well and how the service helped you.",
    "reviews.name": "Your name",
    "reviews.email": "Your email",
    "reviews.rating": "Rating",
    "reviews.message": "Your testimonial",
    "reviews.messagePh": "Tell us about your experience.",
    "reviews.submit": "Send testimonial",
    "reviews.thanks": "Thank you for helping local customers make informed cleaning choices. All testimonials are reviewed before publication.",
    "reviews.secH": "Why the reviews page matters",
    "reviews.secP": "It reinforces the most important sales message from the business plan: clients buy trust, peace of mind and someone dependable.",
    "reviews.nextEye": "Next step",
    "reviews.nextH": "Use this page to support Google and Facebook growth",
    "reviews.nextP": "Once real reviews are collected, replace placeholder copy with genuine feedback and keep the same layout.",
    "contact.eyebrow": "Contact Us",
    "contact.h1": "Contact AGU Clean Services",
    "contact.lead": "Get a free quote by phone, WhatsApp or contact form. We aim to respond quickly and clearly.",
    "contact.callLabel": "Call / WhatsApp",
    "contact.emailLabel": "Email",
    "contact.areaLabel": "Service Area",
    "contact.ownerLabel": "Owner",
    "contact.ownerName": "Agnieszka Kalina",
    "contact.servicesValue": "Domestic • Commercial • Tenancy • Airbnb",
    "contact.areas": "Newcastle • Gateshead • Chester-le-Street • Durham",
    "contact.formH": "Request your free quote",
    "contact.formP": "Send your service type, property details and preferred contact method. We will get back to you quickly with a tailored quote.",
    "contact.name": "Full name",
    "contact.namePh": "Your name",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.select": "Select service",
    "contact.message": "Property details",
    "contact.messagePh": "Property size, location and any details that help with the quote",
    "contact.hoursLabel": "Working Hours",
    "contact.hoursValue": "Monday-Saturday 8:00-18:00, flexible by arrangement",
    "contact.websiteLabel": "Website",
    "contact.flowH": "Quote and booking process",
    "contact.flowP": "A clear route from enquiry to confirmed booking keeps the service professional and easy to trust.",
    "contact.flow1H": "1. Free quote",
    "contact.flow1P": "Send the property type, location and service needed by phone, WhatsApp or the website form.",
    "contact.flow2H": "2. Booking slot",
    "contact.flow2P": "Jobs are arranged around weekly visits, tenancy deadlines, guest turnovers and business hours.",
    "contact.flow3H": "3. Confirmed service",
    "contact.flow3P": "You receive a clear next step, agreed timing and a professional service plan.",
    "contact.send": "Get a Free Quote",
    "areas.eyebrow": "Areas We Cover",
    "areas.h1": "Cleaning services across Gateshead and nearby areas",
    "areas.lead": "AGU Clean Services supports homes, rental properties and small business spaces with dependable cleaning and flexible booking.",
    "areas.introH": "Local service, practical coverage",
    "areas.introP": "We focus on clear communication, reliable attendance and professional results across our core coverage area.",
    "areas.card1h": "Gateshead",
    "areas.card1p": "Domestic cleaning, deep cleaning and regular weekly or fortnightly bookings.",
    "areas.card2h": "Newcastle",
    "areas.card2p": "Home, office and end of tenancy cleaning with quick quote support.",
    "areas.card3h": "Chester-le-Street",
    "areas.card3p": "Flexible service for homes, landlords and one-off deep clean requests.",
    "areas.card4h": "Durham",
    "areas.card4p": "Rental property, domestic and small commercial cleaning by arrangement.",
    "areas.listH": "Services available across these areas",
    "areas.list1": "Domestic Cleaning",
    "areas.list2": "Deep Cleaning",
    "areas.list3": "End of Tenancy Cleaning",
    "areas.list4": "Office Cleaning",
    "areas.list5": "Regular Weekly Cleaning",
    "areas.list6": "Fortnightly Cleaning",
    "areas.list7": "One-Off Cleaning",
    "areas.ctaH": "Need to check your postcode or request a quote?",
    "areas.ctaP": "Contact us today and we will confirm availability, service scope and the best booking option for your property.",
    "privacy.eyebrow": "Privacy Policy",
    "privacy.h1": "Privacy Policy",
    "privacy.lead": "This page explains how AGU Clean Services handles website enquiries and basic client data.",
    "privacy.whoH": "Data Controller Information",
    "privacy.whoP": "For the purpose of the UK General Data Protection Regulation (UK GDPR) and the Data Protection Act 2018, the data controller is Agnieszka Kalina vel Kalinowska, operating as a sole trader under the business name AGU Clean Services.",
    "privacy.contactH": "Contact Email",
    "privacy.contactP": "agucleanservices@gmail.com",
    "privacy.collectH": "What information we collect",
    "privacy.collectP": "When you use the contact form or request a quote, we may collect your name, phone number, email address, service request and property details.",
    "privacy.useH": "How we use your information",
    "privacy.useP": "Your information is used only to reply to enquiries, prepare quotes, arrange bookings and manage client communication.",
    "privacy.shareH": "Data sharing",
    "privacy.shareP": "Your data is not sold. Information is only shared where reasonably necessary to provide the requested cleaning service or comply with legal obligations.",
    "privacy.rightsH": "Your rights",
    "privacy.rightsP": "You may request access, correction or deletion of your enquiry data by contacting us by email.",
    "terms.eyebrow": "Terms & Conditions",
    "terms.h1": "Terms and Conditions",
    "terms.lead": "These terms outline the basic booking and service conditions for AGU Clean Services.",
    "terms.quotesH": "Quotes and bookings",
    "terms.quotesP": "Quotes are based on property size, condition, location and requested service. Final scope can be confirmed before the booking starts.",
    "terms.accessH": "Access and preparation",
    "terms.accessP": "Clients should provide safe access to the property and share any important information before the visit, including timing restrictions or parking details.",
    "terms.standardH": "Service standard",
    "terms.standardP": "Cleaning work is completed with reasonable care and professional attention. Results may vary depending on property condition and time booked.",
    "terms.cancelH": "Cancellations",
    "terms.cancelP": "Please provide as much notice as possible if a booking needs to be changed or cancelled.",
    "terms.paymentH": "Payments",
    "terms.paymentP": "Payment terms can be agreed during booking. Commercial or specialist work may require a separate written quote.",
    "terms.liabilityH": "Liability",
    "terms.liabilityP": "Any issue should be reported promptly after the visit so it can be reviewed and addressed fairly."
  },
  pl: {
    "nav.home": "Strona glowna",
    "nav.about": "O nas",
    "nav.areas": "Obszar dzialania",
    "nav.aboutMe": "O mnie",
    "nav.services": "Uslugi",
    "nav.prices": "Cennik",
    "nav.reviews": "Opinie",
    "nav.faq": "FAQ",
    "nav.contact": "Kontakt",
    "nav.privacy": "Polityka prywatnosci",
    "nav.terms": "Regulamin",
    "nav.search": "Szukaj na stronie",
    "nav.call": "Zadzwon teraz",
    "nav.whatsapp": "WhatsApp",
    "home.eyebrow": "Lokalna, rzetelna firma sprzatajaca",
    "home.h1": "Profesjonalne sprzatanie z dopracowanym, spokojnym efektem.",
    "home.lead": "AGU Clean Services pomaga utrzymac domy, biura i nieruchomosci na wynajem w czystosci, porzadku i gotowosci do codziennego uzytku w Newcastle, Gateshead i Durham.",
    "home.cta1": "Darmowa wycena",
    "home.cta2": "Zobacz uslugi",
    "home.point1": "✔ Sprzatanie domowe i komercyjne",
    "home.point2": "✔ Elastyczne wizyty cykliczne lub jednorazowe",
    "home.point3": "✔ Sprzatanie po najmie i obsluga Airbnb",
    "home.point4": "✔ Przyjazna i niezawodna lokalna usluga",
    "home.quick": "Szybki kontakt",
    "home.quickText": "Darmowe wyceny sa dostepne przez telefon, WhatsApp lub formularz kontaktowy.",
    "home.area1": "Glowny obszar dzialania",
    "home.area2": "Elastyczne lokalne terminy",
    "home.area3": "Zlecenia domowe i po najmie",
    "home.quote": "Darmowa wycena",
    "home.quoteText": "Szybka odpowiedz na WhatsApp",
    "home.trust1h": "Rzetelna usluga",
    "home.trust1p": "Pewnie i konsekwentnie",
    "home.trust2h": "Elastyczne godziny",
    "home.trust2p": "Opcje w tygodniu i po godzinach",
    "home.trust3h": "Dom i firma",
    "home.trust3p": "Domy, biura i wynajem",
    "home.trust4h": "Jasne wyceny",
    "home.trust4p": "Bez ukrytych kosztow",
    "home.servicesH": "Uslugi sprzatania dopasowane do realnych potrzeb klientow",
    "home.servicesP": "Proste kategorie uslug, jasna komunikacja i elastyczne terminy sprawiaja, ze firmie latwo zaufac i latwo ja zarezerwowac.",
    "svc.domestic.h": "Sprzatanie domowe",
    "svc.domestic.p": "Regularne cotygodniowe lub dwutygodniowe sprzatanie domu nastawione na komfort, powtarzalnosc i codzienny porzadek.",
    "svc.deep.h": "Gruntowne sprzatanie",
    "svc.deep.p": "Dokladne sprzatanie calej nieruchomosci, kuchni, lazienek i trudniejszych stref wymagajacych resetu.",
    "svc.tenancy.h": "Sprzatanie po najmie",
    "svc.tenancy.p": "Sprzatanie po wyprowadzce przygotowane pod przekazanie nieruchomosci i wynajem.",
    "svc.commercial.h": "Sprzatanie komercyjne",
    "svc.commercial.p": "Biura, salony, sklepy i male firmy utrzymane w czystosci i gotowe na klientow.",
    "svc.airbnb.h": "Sprzatanie Airbnb",
    "svc.airbnb.p": "Szybkie przygotowanie nieruchomosci krotkoterminowych pomiedzy pobytami gosci.",
    "svc.venues.h": "Lokale po godzinach",
    "svc.venues.p": "Wsparcie sprzatajace dla klubow, pubow i lokali wymagajacych elastycznych godzin.",
    "home.whyH": "Dlaczego klienci wybieraja AGU Clean Services",
    "home.whyP": "Firma powinna sprawiac wrazenie spokojnej, godnej zaufania i profesjonalnej. Zaczyna sie to od jasnych cen, sprawnego kontaktu i niezawodnego standardu pracy.",
    "home.why1": "✔ Skupienie na praktycznych uslugach dla klienta",
    "home.why2": "✔ Odpowiednie dla domow, biur, najmu i Airbnb",
    "home.why3": "✔ Przyjazna komunikacja bez korporacyjnego tonu",
    "home.why4": "✔ Dobra podstawa pod polecenia i stalych klientow",
    "home.aboutEyebrow": "O Agnieszce",
    "home.aboutH": "Przyjazna usluga z profesjonalnym standardem.",
    "home.aboutP": "AGU Clean Services to rzetelna lokalna firma, ktora stawia na zaufanie, punktualnosc i efekt czystosci odczuwalny od razu.",
    "home.about1": "✔ Lokalna usluga dla Newcastle, Gateshead i Durham",
    "home.about2": "✔ Jasna komunikacja przez telefon i WhatsApp",
    "home.about3": "✔ Elastyczne wyceny wedlug wielkosci i zakresu pracy",
    "home.pricingH": "Proste i jasne ceny startowe",
    "home.pricingP": "Widoczne ceny startowe sprawiaja, ze strona wyglada profesjonalnie, a jednoczesnie pozostawiaja elastycznosc wyceny wedlug metrazu, stanu i zakresu pracy.",
    "price.regular.h": "Sprzatanie regularne",
    "price.regular.p": "Wizyty co tydzien lub co dwa tygodnie",
    "price.regular.d": "Biezace utrzymanie domu i rutynowe sprzatanie.",
    "price.deep.h": "Gruntowne sprzatanie",
    "price.deep.p": "Zalezy od wielkosci nieruchomosci",
    "price.deep.d": "Dokladny reset kuchni, lazienek i calego domu.",
    "price.tenancy.h": "Sprzatanie po najmie",
    "price.tenancy.p": "Standard pod wyprowadzke",
    "price.tenancy.d": "Przygotowane pod wlascicieli, agentow i przekazanie lokalu.",
    "price.commercial.h": "Komercyjne",
    "price.commercial.p": "Dostepny elastyczny grafik",
    "price.commercial.d": "Biura, salony, sklepy i male firmy.",
    "home.reviewsH": "Lokalne zaufanie i przyjazna, rzetelna usluga",
    "home.reviewsP": "Opinie powinny wzmacniac to, co obiecuje marka: zaufanie, sprawny kontakt i czysty efekt bez stresu.",
    "home.rev1": "Bardzo profesjonalnie i latwo wszystko ustalic. Mieszkanie wygladalo swiezo, czysto i bylo od razu gotowe.",
    "home.rev2": "Rzetelna usluga i dobra komunikacja. Dokladnie taki typ osoby, ktora mozna spokojnie polecic dalej.",
    "home.rev3": "Bardzo pomocne przy sprzataniu po najmie i wykonane na mocnym poziomie bez problemow.",
    "home.ctaBandH": "Potrzebujesz rzetelnej osoby do sprzatania domu, biura lub wynajmu?",
    "home.ctaBandP": "Przejdz do strony kontaktowej po darmowa wycene lub napisz na WhatsApp, aby szybko otrzymac odpowiedz.",
    "home.ctaBand1": "Przejdz do kontaktu",
    "home.ctaBand2": "Zobacz ceny",
    "dashboard.panelH": "Panel operacyjny uslug",
    "dashboard.panelP": "Przejrzysty podglad jednego ekranu pokazujacy biezacy przeplyw uslug, zapytania i kontekst rezerwacji.",
    "dashboard.panelPoint1": "✔ Aktywne podsumowanie uslug i kolejny krok",
    "dashboard.panelPoint2": "✔ Bezposrednie przejscie z uslug do zapytania",
    "dashboard.panelPoint3": "✔ Przejrzysty obraz operacyjny usprawniajacy decyzje",
    "dashboard.panelVisualAlt": "Premium design token board",
    "dashboard.panelVisualCaption": "Panel tokenow designu stworzony do premium, czytelnego UX.",
    "dashboard.openPanel": "Otworz panel",
    "dashboard.manageServices": "Zobacz uslugi",
    "dashboard.contactForm": "Przejdz do formularza kontaktowego",
    "dashboard.contactPanelP": "Trasa przez dashboard utrzymuje statusy leadów i kontekst uslugi widoczne w calym procesie klienta.",
    "dashboard.airbnbLink": "Strona uslugi Airbnb",
    "dashboard.contactNow": "Potrzebujesz pomocy? Kontakt",
    "dashboard.panelCaption": "Podglad operacyjny dla stabilniejszej i bardziej zaufanej uslugi.",
    "dashboard.brandPanelP": "Spojnosc marki rośnie, gdy kazdy krok uslugi polacza sie z panelem operacyjnym i jasna sciezka dzialania.",
    "footer.desc": "Rzetelne, profesjonalne i przystepne cenowo uslugi sprzatania dla domow i firm w Gateshead i okolicach.",
    "footer.pages": "Menu glowne",
    "footer.legal": "Dokumenty",
    "footer.contact": "Kontakt",
    "footer.note": "© 2026 AGU Clean Services. Wszelkie prawa zastrzezone.",
    "footer.trade": "AGU Clean Services jest nazwa handlowa Agnieszki Kaliny vel Kalinowskiej.",
    "about.eyebrow": "O firmie",
    "about.h1": "Lokalna marka sprzatajaca zaprojektowana tak, by wygladac profesjonalnie i budzic zaufanie.",
    "about.lead": "AGU Clean Services jest pozycjonowana jako rzetelna lokalna firma dla sprzatania domowego, wynajmu i malych firm, z dopracowanym i spokojnym wizerunkiem.",
    "about.sec1h": "Zbudowane wokol zaufania, powtarzalnosci i jasnej komunikacji",
    "about.sec1p": "Plan biznesowy jest prosty: ludzie nie kupuja tylko sprzatania. Kupują spokoj, niezawodnosc i osobe, ktora ich nie zawiedzie.",
    "about.list1": "✔ Lokalny fokus na Newcastle, Gateshead i Durham",
    "about.list2": "✔ Premium prezentacja bez chlodnego korporacyjnego jezyka",
    "about.list3": "✔ Jasne kategorie uslug zrozumiale od razu",
    "about.list4": "✔ Dobre dopasowanie do klientow regularnych i kontaktow property",
    "about.coreEye": "Glowne pozycjonowanie",
    "about.coreH": "Przyjazna i profesjonalna firma",
    "about.coreP": "Strona, styl kontaktu i struktura uslug sa zaprojektowane tak, aby od pierwszej wizyty wygladac uczciwie, profesjonalnie i przystepnie.",
    "about.core1": "✔ Rzetelna i przyjazna usluga",
    "about.core2": "✔ Elastyczne terminy i proste wyceny",
    "about.core3": "✔ Mocny branding do ogloszen online i polecen",
    "about.oppH": "Najlepsze mozliwosci biznesowe",
    "about.oppP": "Najmocniejsze obszary wzrostu z planu biznesowego to regularne sprzatanie domowe, sprzatanie po najmie, obsluga Airbnb i kontakt z lokalnymi agentami nieruchomosci.",
    "about.card1h": "Stali klienci domowi",
    "about.card1p": "Cotygodniowe i dwutygodniowe wizyty pomagaja budowac stabilny przychod i lokalne polecenia.",
    "about.card2h": "Sprzatanie po najmie",
    "about.card2p": "Wyzej wyceniane zlecenia dobrze dopasowane do agentow, wlascicieli i terminow zakonczenia najmu.",
    "about.card3h": "Wsparcie Airbnb",
    "about.card3p": "Reset nieruchomosci krotkoterminowych daje elastycznosc i pomaga budowac relacje z hostami i managerami.",
    "about.storyH": "Marka zaprojektowana tak, aby dawala poczucie spokoju, dopracowania i prawdziwej rzetelnosci.",
    "about.storyP": "AGU Clean Services jest zbudowane tak, aby wygladac bardziej profesjonalnie niz typowa mala strona firmy sprzatajacej. Celem jest stworzenie wrazenia uslugi przyjaznej, lokalnej i przystepnej, ale nadal premium i godnej zaufania.",
    "about.story1H": "Lokalnie i osobiscie",
    "about.story1P": "Firma jest pozycjonowana dla Newcastle, Gateshead i Durham jako lokalna marka o bardziej osobistym charakterze niz korporacyjna konkurencja.",
    "about.story2H": "Profesjonalny standard",
    "about.story2P": "Klienci nadal oczekuja punktualnosci, dopracowanego efektu, dobrej komunikacji i poziomu, na ktorym mozna polegac za kazdym razem.",
    "about.story3H": "Budowane pod dlugie zaufanie",
    "about.story3P": "Celem nie jest tylko jednorazowe sprzatanie. Celem sa powroty klientow, polecenia i mocna reputacja budowana przez konsekwencje.",
    "about.clientsH": "Dla kogo ta usluga jest najlepsza",
    "about.clientsP": "Plan biznesowy jest najmocniejszy tam, gdzie istnieje jasna i powtarzalna potrzeba: domy, przekazania nieruchomosci po najmie, Airbnb i mniejsze lokale firmowe.",
    "about.clients1": "✔ Zabiegane domy potrzebujace regularnego wsparcia co tydzien lub co dwa tygodnie",
    "about.clients2": "✔ Najemcy, wlasciciele i agenci przygotowujacy nieruchomosc do przekazania",
    "about.clients3": "✔ Hosty Airbnb potrzebujace szybkiego resetu pomiedzy pobytami gosci",
    "about.clients4": "✔ Biura, salony, sklepy i inne mniejsze przestrzenie komercyjne",
    "about.standardEye": "Standard uslugi",
    "about.standardH": "Czego klient powinien oczekiwac za kazdym razem",
    "about.standardP": "Premium lokalna marka sprzatajaca rozwija sie przez konsekwencje. To oznacza jasny kontakt, szacunek do nieruchomosci i widoczny efekt koncowy przy kazdej wizycie.",
    "about.standard1": "✔ Szacunek do domu, biura lub nieruchomosci na wynajem",
    "about.standard2": "✔ Jasne ustalenia dotyczace przyjazdu i prosty kontakt",
    "about.standard3": "✔ Dokladne sprzatanie z widocznym efektem koncowym",
    "about.standard4": "✔ Elastyczne wyceny wedlug wielkosci, stanu i zakresu pracy",
    "about.processH": "Prosty proces, jasna komunikacja i brak zbednych utrudnien",
    "about.processP": "Najlepsze doswiadczenie klienta powinno byc latwe od pierwszej wiadomosci do zakonczonego sprzatania. To takze sprawia, ze firma wyglada bardziej profesjonalnie i budzi wieksze zaufanie.",
    "about.process1H": "1. Zapytanie",
    "about.process1P": "Klient wysyla wiadomosc przez telefon, WhatsApp lub formularz z typem nieruchomosci, lokalizacja i potrzebna usluga.",
    "about.process2H": "2. Wycena",
    "about.process2P": "Przygotowywana jest jasna wycena oparta na wielkosci nieruchomosci, stanie, czestotliwosci i dokladnym zakresie prac.",
    "about.process3H": "3. Wizyta sprzatajaca",
    "about.process3P": "Sprzatanie wykonywane jest z szacunkiem, dokladnoscia i efektem koncowym, ktory daje poczucie swiezosci, porzadku i profesjonalnego wykonania.",
    "about.ctaH": "Chcesz zobaczyc strukture oferty?",
    "about.ctaP": "Przejdz do podstron uslug i cennika, aby zobaczyc finalna publiczna oferte.",
    "aboutme.eyebrow": "O mnie - Agnieszka",
    "aboutme.h1": "Osobista usluga sprzatania oparta na zaufaniu, dokladnosci i konsekwencji.",
    "aboutme.lead": "Mam na imie Agnieszka i prowadze firme sprzatajaca stworzona z pasji do czystych, uporzadkowanych i przyjaznych przestrzeni. Przez wiele lat pracy w domach, mieszkaniach i firmach przekonalam sie, ze w dobrym sprzataniu najwazniejsze sa dbalosc o szczegoly, zaufanie i konsekwencja.",
    "aboutme.workH": "Moja praca",
    "aboutme.workP": "Do kazdego zlecenia podchodze indywidualnie, poswiecajac czas na zrozumienie potrzeb klienta i dopasowanie uslugi tak, aby efekt koncowy spelnial jego oczekiwania.",
    "aboutme.workP2": "Stawiam na rzetelnosc, punktualnosc i wysoka jakosc uslug. Korzystam ze sprawdzonych srodkow i bezpiecznych metod czyszczenia, ktore pomagaja utrzymac swiezosc i czystosc na dluzej.",
    "aboutme.expH": "Doswiadczenie",
    "aboutme.expP": "Przez lata zdobylam doswiadczenie zarowno w domach prywatnych, jak i w przestrzeniach komercyjnych. To nauczylo mnie, jak wazne sa starannosc, precyzja i odpowiedzialnosc na kazdym etapie pracy.",
    "aboutme.exp1": "Wykonywanie kazdego etapu pracy z dokladnoscia i starannoscia",
    "aboutme.exp2": "Szacunek do mienia klienta i jego prywatnej przestrzeni",
    "aboutme.exp3": "Zachowanie dyskrecji i profesjonalizmu przez caly czas",
    "aboutme.exp4": "Sprawna, skuteczna i odpowiedzialna organizacja pracy",
    "aboutme.trustH": "Rzetelnosc i zaufanie",
    "aboutme.trustP": "Moi klienci cenia mnie za rzetelnosc, uczciwosc, dbalosc o szczegoly oraz stale wysoki standard uslug, polaczony z przyjazna komunikacja i profesjonalnym podejsciem.",
    "aboutme.trustP2": "Zaproszenie kogos do domu lub firmy to wazna decyzja. Dlatego zawsze dbam o to, aby wspolpraca byla komfortowa, przejrzysta i oparta na wzajemnym zaufaniu.",
    "aboutme.valuesH": "Co klienci cenia najbardziej",
    "aboutme.values1": "Rzetelnosc i uczciwosc",
    "aboutme.values2": "Dbalosc o szczegoly",
    "aboutme.values3": "Stale wysoki standard uslug",
    "aboutme.values4": "Przyjazna komunikacje i profesjonalne podejscie",
    "aboutme.bandH": "AGU Clean Services",
    "aboutme.bandP": "Rzetelne sprzatanie. Profesjonalny efekt.",
    "aboutme.bandP2": "Dom - Biuro - Sprzatanie komercyjne",
    "aboutme.bandP3": "Obsluga Newcastle, Gateshead, Chester-le-Street i Durham.",
    "services.eyebrow": "Finalna lista uslug",
    "services.jumpLabel": "Przejdz do uslugi",
    "services.openPage": "Zobacz usluge",
    "services.requestQuote": "Popros o wycene",
    "services.openSection": "Przejdz do sekcji uslugi",
    "services.h1": "Jasne uslugi dla domow, wynajmu i malych firm.",
    "services.lead": "Oferta jest ulozona tak, aby byla czytelna na pierwszy rzut oka i mocna zarowno dla klientow prywatnych, jak i zlecen property.",
    "services.card1H": "Sprzatanie domowe",
    "services.card1P": "Cotygodniowe lub co dwutygodniowe sprzatanie domu dla biezacego utrzymania i stalego efektu swiezosci.",
    "services.card2H": "Generalne sprzatanie",
    "services.card2P": "Dokladne sprzatanie kuchni, lazienki i calego domu, gdy standardowa usluga to za malo.",
    "services.card3H": "Sprzatanie po najmie",
    "services.card3P": "Sprzatanie po wyprowadzce dla najemcow, wlascicieli i agentow potrzebujacych mocniejszego standardu prezentacji.",
    "services.card4H": "Sprzatanie komercyjne",
    "services.card4P": "Biura, sklepy, salony i male lokale z elastycznym grafikiem dopasowanym do firmy.",
    "services.card5H": "Sprzatanie Airbnb",
    "services.card5P": "Sprzatanie i przygotowanie nieruchomosci pomiedzy pobytami gosci w wynajmie krotkoterminowym.",
    "services.detailH": "Kazda usluga opisana jak osobna oferta",
    "services.detailP": "Kazdy blok ponizej dziala jak osobna podstrona uslugowa, dzieki czemu klient szybko rozumie zakres, zastosowanie i najlepszy moment na dana usluge.",
    "services.domesticH": "Sprzatanie domowe",
    "services.domesticP": "Regularne sprzatanie domowe jest idealne dla klientow, ktorzy chca utrzymac czysty i komfortowy dom bez stresu zwiazanego z robieniem wszystkiego samodzielnie.",
    "services.domesticEye": "Najlepsze dla",
    "services.domesticSub": "Domu, ktory ma byc stale swiezy i zadbany",
    "services.domesticBody": "Ta usluga jest przeznaczona do codziennego utrzymania porzadku i pomaga klientom utrzymac czystosc dzieki regularnym wizytom i dopracowanemu efektowi.",
    "services.domestic1": "✔ Wizyty co tydzien lub co dwa tygodnie",
    "services.domestic2": "✔ Kuchnie, lazienki, kurze i podlogi",
    "services.domestic3": "✔ Najlepsze dla zabieganych domow i stalych klientow",
    "services.deepH": "Generalne sprzatanie",
    "services.deepP": "Bardziej intensywna usluga dla nieruchomosci, ktore potrzebuja prawdziwego resetu, wiekszej dokladnosci i widocznie swiezszego efektu.",
    "services.deepEye": "Dokladne sprzatanie",
    "services.deepSub": "Gdy standardowe sprzatanie nie wystarcza",
    "services.deepBody": "Generalne sprzatanie sprawdza sie przy pierwszych wizytach, sezonowych resetach i nieruchomosciach wymagajacych dokladniejszej pracy w kuchni, lazience i trudniejszych strefach.",
    "services.deep1": "✔ Szczegolna uwaga na kuchnie i lazienki",
    "services.deep2": "✔ Dobre przed wydarzeniami, po intensywnych okresach lub przy pierwszym sprzataniu",
    "services.deep3": "✔ Elastyczny zakres wedlug wielkosci i stanu nieruchomosci",
    "services.tenancyH": "Sprzatanie po najmie",
    "services.tenancyP": "Ta usluga jest przeznaczona do sytuacji po wyprowadzce, kiedy nieruchomosc ma wygladac czysto, schludnie i byc gotowa do przekazania kolejnemu najemcy, wlascicielowi lub agentowi.",
    "services.tenancyEye": "Sprzatanie po wyprowadzce",
    "services.tenancySub": "Przygotowane pod przekazanie nieruchomosci",
    "services.tenancyBody": "To jedna z najwartosciowszych uslug w ofercie, bo rozwiazuje bardzo konkretny problem i dobrze pasuje zarowno do klientow prywatnych, jak i kontaktow property.",
    "services.tenancy1": "✔ Mocniejszy standard prezentacji pod przekazanie",
    "services.tenancy2": "✔ Dla najemcow, wlascicieli i agencji",
    "services.tenancy3": "✔ Dobra tam, gdzie potrzebne jest dokladniejsze wykonczenie",
    "services.airbnbH": "Sprzatanie Airbnb",
    "services.airbnbP": "Praktyczna usluga dla wynajmu krotkoterminowego dla hostow, ktorzy potrzebuja rzetelnego sprzatania i dobrze przygotowanej nieruchomosci pomiedzy pobytami.",
    "services.airbnbEye": "Usluga turnover",
    "services.airbnbSub": "Gotowe na kolejnego goscia",
    "services.airbnbBody": "Sprzatanie Airbnb skupia sie na szybkosci, powtarzalnosci i prezentacji, aby nieruchomosc byla stale gotowa pomiedzy rezerwacjami.",
    "services.airbnb1": "✔ Szybki reset pomiedzy pobytami gosci",
    "services.airbnb2": "✔ Nacisk na prezentacje, czystosc i konsekwencje",
    "services.airbnb3": "✔ Dobre dla hostow i managerow nieruchomosci",
    "services.commercialH": "Sprzatanie komercyjne",
    "services.commercialP": "Sprzatanie komercyjne sprawdza sie w biurach, sklepach, salonach i innych mniejszych przestrzeniach firmowych, ktore potrzebuja czystego i profesjonalnego otoczenia dla pracownikow i klientow.",
    "services.commercialEye": "Przestrzenie firmowe",
    "services.commercialSub": "Czysto, schludnie i latwo do utrzymania",
    "services.commercialBody": "Ta usluga pomaga lokalnym firmom utrzymac bardziej dopracowane otoczenie bez potrzeby duzego korporacyjnego kontraktu sprzatajacego.",
    "services.commercial1": "✔ Biura, salony, sklepy i podobne lokale",
    "services.commercial2": "✔ Elastyczny grafik wokol godzin pracy firmy",
    "services.commercial3": "✔ Rzetelna lokalna opcja do regularnego utrzymania",
    "services.secH": "Jak powinny wygladac podstrony uslug",
    "services.secP": "Taka struktura sprawia, ze marka wyglada na uporzadkowana: widoczne kategorie, praktyczny jezyk i brak zbednego marketingowego wypelnienia.",
    "services.list1": "✔ Bezposrednie nazwy uslug",
    "services.list2": "✔ Krotkie opisy z realnymi zastosowaniami",
    "services.list3": "✔ Latwa droga od uslugi do wyceny",
    "services.flowEye": "Najlepszy flow konwersji",
    "services.flowH": "Strona uslug → cennik → kontakt",
    "services.flowP": "Taki przeplyw dobrze pasuje do lokalnych klientow domowych oraz zapytan od agentow i hostow.",
    "services.ctaH": "Potrzebujesz cen dla jednej z tych uslug?",
    "services.ctaP": "Przejdz do cennika, aby zobaczyc publiczna strukture cen startowych.",
    "prices.eyebrow": "Jasny cennik",
    "prices.h1": "Proste ceny startowe z elastyczna wycena.",
    "prices.lead": "Publiczne stawki szybko buduja zaufanie. Koncowa wycena nadal zalezy od wielkosci nieruchomosci, stanu, czestotliwosci i zakresu pracy.",
    "prices.airbnbH": "Sprzatanie Airbnb",
    "prices.airbnbP": "Od £45 w zaleznosci od wielkosci nieruchomosci i wymagan dotyczacych turnoveru.",
    "prices.freeH": "Darmowe wyceny",
    "prices.freeP": "Klienci moga otrzymac wycene telefonicznie, przez WhatsApp lub formularz kontaktowy.",
    "prices.areaH": "Obszar dzialania",
    "prices.areaP": "Newcastle, Gateshead i Durham, z wycena dopasowana do nieruchomosci i lokalizacji.",
    "prices.ctaH": "Potrzebujesz dokladnej wyceny?",
    "prices.ctaP": "Podaj typ nieruchomosci, lokalizacje i potrzebna usluge, a przygotujemy indywidualna wycene.",
    "prices.back": "Powrot do uslug",
    "reviews.eyebrow": "Opinie",
    "reviews.h1": "Co klienci mowia o AGU Clean Services",
    "reviews.lead": "Przyjazna, rzetelna obsluga i mocny efekt koncowy to standard, ktory chcemy utrzymac przy kazdej realizacji.",
    "reviews.formH": "Dodaj swoja opinie",
    "reviews.formP": "Napisz, co zadzialalo dobrze i jak usluga Ci pomogla.",
    "reviews.name": "Twoje imie",
    "reviews.email": "Twoj email",
    "reviews.rating": "Ocena",
    "reviews.message": "Twoja opinia",
    "reviews.messagePh": "Opisz swoje doswiadczenie.",
    "reviews.submit": "Wyslij opinie",
    "reviews.thanks": "Dziekujemy za pomoc lokalnym klientom w wyborze odpowiedniej uslugi sprzatania. Wszystkie opinie sa sprawdzane przed publikacja.",
    "reviews.secH": "Dlaczego strona opinii ma znaczenie",
    "reviews.secP": "Wzmacnia najwazniejszy komunikat sprzedazowy z planu biznesowego: klienci kupuja zaufanie, spokoj i kogos niezawodnego.",
    "reviews.nextEye": "Nastepny krok",
    "reviews.nextH": "Wykorzystaj te strone do wsparcia Google i Facebook growth",
    "reviews.nextP": "Gdy pojawia sie prawdziwe opinie, zamien teksty tymczasowe na autentyczny feedback i zachowaj ten sam uklad.",
    "contact.eyebrow": "Kontakt",
    "contact.h1": "Skontaktuj sie z AGU Clean Services",
    "contact.lead": "Uzyskaj darmowa wycene przez telefon, WhatsApp lub formularz kontaktowy. Odpowiadamy szybko i konkretnie.",
    "contact.callLabel": "Telefon / WhatsApp",
    "contact.emailLabel": "Email",
    "contact.areaLabel": "Obszar dzialania",
    "contact.ownerLabel": "Wlasciciel",
    "contact.ownerName": "Agnieszka Kalina",
    "contact.servicesValue": "Domowe • Komercyjne • Po najmie • Airbnb",
    "contact.areas": "Newcastle • Gateshead • Chester-le-Street • Durham",
    "contact.formH": "Popros o darmowa wycene",
    "contact.formP": "Podaj typ nieruchomosci, lokalizacje i potrzebna usluge. Ten uklad jest gotowy pod przyszla integracje backendu.",
    "contact.name": "Imie i nazwisko",
    "contact.namePh": "Twoje imie",
    "contact.phone": "Telefon",
    "contact.email": "Email",
    "contact.select": "Wybierz usluge",
    "contact.message": "Szczegoly nieruchomosci",
    "contact.messagePh": "Wielkosc nieruchomosci, lokalizacja i wszystkie informacje pomocne do wyceny",
    "contact.hoursLabel": "Godziny pracy",
    "contact.hoursValue": "Poniedzialek-sobota 8:00-18:00, godziny elastyczne po uzgodnieniu",
    "contact.websiteLabel": "Strona internetowa",
    "contact.flowH": "Proces wyceny i rezerwacji",
    "contact.flowP": "Jasna droga od zapytania do potwierdzonej rezerwacji sprawia, ze usluga wyglada profesjonalnie i wzbudza zaufanie.",
    "contact.flow1H": "1. Darmowa wycena",
    "contact.flow1P": "Wyslij typ nieruchomosci, lokalizacje i potrzebna usluge telefonicznie, przez WhatsApp lub formularz.",
    "contact.flow2H": "2. Termin",
    "contact.flow2P": "Zlecenia sa ustalane wokol regularnych wizyt, terminow wyprowadzki, turnoverow gosci i godzin pracy firmy.",
    "contact.flow3H": "3. Potwierdzona usluga",
    "contact.flow3P": "Otrzymujesz jasny kolejny krok, ustalony termin i profesjonalny plan realizacji.",
    "contact.send": "Uzyskaj darmowa wycene",
    "areas.eyebrow": "Obszar dzialania",
    "areas.h1": "Uslugi sprzatania w Gateshead i okolicach",
    "areas.lead": "AGU Clean Services wspiera domy, nieruchomosci na wynajem i male firmy rzetelnym sprzataniem oraz elastycznymi terminami.",
    "areas.introH": "Lokalna obsluga i praktyczny zasieg",
    "areas.introP": "Skupiamy sie na jasnej komunikacji, punktualnosci i profesjonalnym efekcie w naszym glownym obszarze dzialania.",
    "areas.card1h": "Gateshead",
    "areas.card1p": "Sprzatanie domowe, deep cleaning oraz regularne wizyty tygodniowe lub co dwa tygodnie.",
    "areas.card2h": "Newcastle",
    "areas.card2p": "Sprzatanie domow, biur i po najmie z szybka wycena.",
    "areas.card3h": "Chester-le-Street",
    "areas.card3p": "Elastyczna obsluga dla domow, wynajmujacych i jednorazowych generalnych porzadkow.",
    "areas.card4h": "Durham",
    "areas.card4p": "Sprzatanie nieruchomosci na wynajem, domow i malych lokali komercyjnych po uzgodnieniu.",
    "areas.listH": "Uslugi dostepne w tych lokalizacjach",
    "areas.list1": "Sprzatanie domowe",
    "areas.list2": "Deep cleaning",
    "areas.list3": "Sprzatanie po najmie",
    "areas.list4": "Sprzatanie biur",
    "areas.list5": "Cotygodniowe sprzatanie",
    "areas.list6": "Sprzatanie co dwa tygodnie",
    "areas.list7": "Jednorazowe sprzatanie",
    "areas.ctaH": "Chcesz sprawdzic swoj kod pocztowy lub poprosic o wycene?",
    "areas.ctaP": "Skontaktuj sie z nami, a potwierdzimy dostepnosc, zakres uslugi i najlepszy termin dla Twojej nieruchomosci.",
    "privacy.eyebrow": "Polityka prywatnosci",
    "privacy.h1": "Polityka prywatnosci",
    "privacy.lead": "Ta strona wyjasnia, jak AGU Clean Services przetwarza zapytania ze strony i podstawowe dane klienta.",
    "privacy.whoH": "Informacja o administratorze danych",
    "privacy.whoP": "Na potrzeby UK GDPR oraz Data Protection Act 2018 administratorem danych jest Agnieszka Kalina vel Kalinowska, prowadzaca dzialalnosc jako sole trader pod nazwa AGU Clean Services.",
    "privacy.contactH": "Email kontaktowy",
    "privacy.contactP": "agucleanservices@gmail.com",
    "privacy.collectH": "Jakie informacje zbieramy",
    "privacy.collectP": "Gdy korzystasz z formularza kontaktowego lub prosisz o wycene, mozemy zbierac imie, numer telefonu, adres email, rodzaj uslugi i szczegoly nieruchomosci.",
    "privacy.useH": "Jak wykorzystujemy informacje",
    "privacy.useP": "Twoje dane sa wykorzystywane wylacznie do odpowiedzi na zapytania, przygotowania wycen, organizacji rezerwacji i kontaktu z klientem.",
    "privacy.shareH": "Udostepnianie danych",
    "privacy.shareP": "Nie sprzedajemy danych. Informacje sa udostepniane tylko wtedy, gdy jest to rozsadnie konieczne do wykonania uslugi lub spelnienia obowiazkow prawnych.",
    "privacy.rightsH": "Twoje prawa",
    "privacy.rightsP": "Mozesz poprosic o dostep, poprawienie lub usuniecie danych przesylajac wiadomosc email.",
    "terms.eyebrow": "Regulamin",
    "terms.h1": "Warunki i zasady",
    "terms.lead": "Te warunki okreslaja podstawowe zasady rezerwacji i realizacji uslug AGU Clean Services.",
    "terms.quotesH": "Wyceny i rezerwacje",
    "terms.quotesP": "Wyceny sa oparte na wielkosci nieruchomosci, jej stanie, lokalizacji i rodzaju uslugi. Ostateczny zakres mozna potwierdzic przed rozpoczeciem pracy.",
    "terms.accessH": "Dostep i przygotowanie",
    "terms.accessP": "Klient powinien zapewnic bezpieczny dostep do nieruchomosci i przekazac wazne informacje przed wizyta, w tym ograniczenia czasowe lub szczegoly parkingu.",
    "terms.standardH": "Standard uslugi",
    "terms.standardP": "Sprzatanie jest wykonywane z nalezyta starannoscia i profesjonalna uwaga. Efekty moga sie roznic w zaleznosci od stanu nieruchomosci i zarezerwowanego czasu.",
    "terms.cancelH": "Anulowanie",
    "terms.cancelP": "Jesli wizyta musi zostac zmieniona lub odwolana, prosimy o mozliwie wczesniejsza informacje.",
    "terms.paymentH": "Platnosci",
    "terms.paymentP": "Warunki platnosci sa ustalane podczas rezerwacji. Prace komercyjne lub specjalistyczne moga wymagac osobnej pisemnej wyceny.",
    "terms.liabilityH": "Odpowiedzialnosc",
    "terms.liabilityP": "Kazdy problem powinien zostac zgloszony niezwlocznie po wizycie, aby mozna bylo go uczciwie sprawdzic i rozwiazac."
  }
};

function applyLanguage(lang) {
  const legacyPolishTextMap = {
    "Home": "Strona główna",
    "About": "O nas",
    "About Me": "O mnie",
    "Services": "Usługi",
    "Prices": "Cennik",
    "Reviews": "Opinie",
    "Contact": "Kontakt",
    "FAQ": "FAQ",
    "Admin": "Panel",
    "Dashboard": "Panel sterowania",
    "Regular cleaning": "Sprzątanie regularne",
    "Deep cleaning": "Generalne sprzątanie",
    "End of tenancy": "Sprzątanie po najmie",
    "Commercial cleaning": "Sprzątanie komercyjne",
    "Airbnb cleaning": "Sprzątanie Airbnb",
    "Open service page": "Zobacz usługę",
    "Request Quote": "Poproś o wycenę",
    "Jump to service:": "Przejdź do usługi:",
    "Final Service List": "Końcowa lista usług",
    "Domestic cleaning": "Sprzątanie domowe",
    "Domestic Service": "Usługa domowa",
    "Detailed Reset": "Generalny reset",
    "Property Handover": "Przekazanie nieruchomości",
    "Business Spaces": "Przestrzenie biznesowe",
    "Turnaround Support": "Wsparcie przy turnoverze",
    "The business plan is specific to local growth and repeat clients.": "Plan biznesowy jest dedykowany wzrostowi lokalnemu i klientom powracającym.",
    "Client Reviews": "Opinie klientów",
    "Leave a Review": "Zostaw opinię",
    "Share your opinion with the AGU Clean Services team.": "Podziel się opinią z zespołem AGU Clean Services.",
    "Add your review": "Dodaj opinię",
    "Tell us what you liked, what we can improve, and rate your service.": "Napisz, co Ci się podobało, co możemy poprawić i oceń naszą usługę.",
    "Your name": "Twoje imię",
    "Your email": "Twój e-mail",
    "Your opinion": "Twoja opinia",
    "Tell us about your experience.": "Opowiedz nam o swoim doświadczeniu.",
    "Add review": "Dodaj opinię",
    "Thank you for helping local customers make better cleaning choices. All opinions are reviewed before publication.": "Dziękujemy za pomoc klientom w lepszym wyborze sprzątania. Wszystkie opinie są moderowane przed publikacją.",
    "Request your free quote": "Poproś o darmową wycenę",
    "Get your free quote today. We usually respond within 1 to 2 hours by WhatsApp, phone or contact form.": "Uzyskaj darmową wycenę już dziś. Zazwyczaj odpowiadamy w ciągu 1-2 godzin przez WhatsApp, telefon lub formularz.",
    "Owner": "Właściciel",
    "Working Hours": "Godziny pracy",
    "Monday-Saturday 8:00-18:00, flexible by arrangement": "Poniedziałek-sobota 8:00-18:00, godziny elastyczne po uzgodnieniu",
    "Website": "Strona internetowa",
    "Quote and Booking Flow": "Przepływ zapytania i rezerwacji",
    "This contact page now reflects the real booking route from the business plan instead of reading like a generic template form.": "Ta strona kontaktu odzwierciedla rzeczywisty proces rezerwacji z planu biznesowego, zamiast wyglądać jak ogólny szablon.",
    "1. Free quote": "1. Darmowa wycena",
    "Send the property type, location and service needed by phone, WhatsApp or the website form.": "Prześlij typ nieruchomości, lokalizację i potrzebną usługę telefonicznie, przez WhatsApp albo formularz na stronie.",
    "2. Booking slot": "2. Termin",
    "Jobs are arranged around weekly domestic visits, tenancy deadlines, guest turnovers and business hours.": "Zlecenia są planowane wokół cotygodniowych wizyt domowych, terminów wyprowadzki, turnoverów gości i godzin pracy.",
    "3. Confirmed service": "3. Potwierdzona usługa",
    "The enquiry flow stays calm and official, with clear next steps and a more trustworthy presentation.": "Przepływ zapytań pozostaje przejrzysty i profesjonalny, z jasnymi kolejnymi krokami oraz bardziej wiarygodną prezentacją.",
    "No leads loaded yet.": "Brak jeszcze zgłoszeń.",
    "No quote enquiries yet.": "Brak jeszcze zapytań o wycenę.",
    "No review enquiries yet.": "Brak jeszcze zapytań z opiniami.",
    "All opinions are reviewed before publication.": "Wszystkie opinie są moderowane przed publikacją.",
    "Our Pricing": "Nasz cennik",
    "Transparent, competitive prices with free quotes always available.": "Przejrzyste, konkurencyjne ceny z darmową wyceną zawsze dostępną.",
    "Regular Domestic Cleaning": "Sprzątanie domowe",
    "Regular Domestic Cleaning": "Sprzątanie domowe",
    "From £25/hour": "Od 25 £/h",
    "Weekly or fortnightly schedule": "Harmonogram co tydzień albo co dwa tygodnie",
    "Deep Cleaning": "Sprzątanie generalne",
    "From £120": "Od 120 £",
    "Full property clean, around 4-8 hours": "Pełne czyszczenie nieruchomości, około 4-8 godzin",
    "End of Tenancy Cleaning": "Sprzątanie po najmie",
    "From £180": "Od 180 £",
    "Move-out clean to agent standard": "Sprzątanie po wyprowadzce do standardu pośrednika",
    "Office and Commercial Cleaning": "Sprzątanie biur i lokali firmowych",
    "From £25/hour": "Od 25 £/h",
    "Offices, shops and salons": "Biura, sklepy i salony",
    "Airbnb & Short-Term Rental Cleaning": "Sprzątanie Airbnb i mieszkań krótkoterminowych",
    "From £45": "Od 45 £",
    "Pubs, Clubs & Hospitality Venues": "Puby, kluby i miejsca gastronomiczne",
    "From £80": "Od 80 £",
    "Free Quotes": "Darmowe wyceny",
    "All prices are guide prices only.": "Wszystkie ceny to widełki orientacyjne.",
    "Need a tailored quote?": "Potrzebujesz dopasowanej wyceny?",
    "Tell us the property type, location and service needed, and we will prepare a clear quote with no hidden costs.": "Podaj typ nieruchomości, lokalizację i potrzebną usługę, a przygotujemy jasną wycenę bez ukrytych opłat.",
    "Get Free Quote": "Uzyskaj darmową wycenę",
    "Back to Services": "Powrót do usług",
    "Domestic Service for a calm, consistently tidy home.": "Sprzątanie domowe dla spokojnego, zawsze czystego domu.",
    "Commercial": "Komercyjne",
    "Client Reviews": "Opinie klientów",
    "Frequently asked questions": "Najczęściej zadawane pytania",
    "Answers about booking, pricing, payment methods, service areas and what to expect from AGU Clean Services.": "Odpowiedzi na pytania o rezerwację, ceny, metody płatności, obszar usług i to, czego możesz się spodziewać.",
    "How do I get a quote?": "Jak mogę uzyskać wycenę?",
    "Do you offer free quotes?": "Czy oferujecie darmowe wyceny?",
    "Yes. Every quote is free and comes with no obligation.": "Tak. Każda wycena jest darmowa i nie zobowiązuje do zakupu.",
    "Are you insured?": "Czy macie ubezpieczenie?",
    "Yes. We hold full public liability insurance.": "Tak. Posiadamy pełne ubezpieczenie OC działalności.",
    "What payment methods do you accept?": "Jakie metody płatności akceptujecie?",
    "Cash, bank transfer, PayPal and Revolut are all accepted.": "Akceptujemy gotówkę, przelew bankowy, PayPal i Revolut.",
    "Are prices fixed?": "Czy ceny są stałe?",
    "Prices depend on the size of the property and the exact scope of work.": "Ceny zależą od wielkości nieruchomości i dokładnego zakresu prac.",
    "Are there any hidden charges?": "Czy pojawiają się ukryte opłaty?",
    "No. The price agreed before the booking is the final price for the agreed scope.": "Nie. Cena ustalona przed rezerwacją jest ostateczna dla zaakceptowanego zakresu.",
    "What are your working hours?": "Jakie są wasze godziny pracy?",
    "Monday to Saturday, 8:00 to 18:00. Evenings and Sundays can be arranged on request.": "Od poniedziałku do soboty, 8:00-18:00. Wieczory i niedziele możliwe po uzgodnieniu.",
    "Do I need to be at home during cleaning?": "Czy muszę być w domu podczas sprzątania?",
    "No. You can leave a key or access code. We work with full trust and discretion.": "Nie. Możesz zostawić klucz lub kod dostępu. Pracujemy z pełnym zaufaniem i dyskrecją.",
    "Do you bring your own cleaning products?": "Czy korzystacie z własnych środków czyszczących?",
    "Yes. Professional products are provided, but we can also use yours if you prefer.": "Tak. Używamy profesjonalnych środków, ale możemy też skorzystać z Twoich, jeśli wolisz.",
    "Which areas do you cover?": "Jakie obszary obsługujecie?",
    "Newcastle, Gateshead, Chester-le-Street and Durham are the main service areas. Nearby locations can be discussed during the quote.": "Głównymi obszarami obsługi są Newcastle, Gateshead, Chester-le-Street i Durham. Sąsiednie lokalizacje omówimy podczas wyceny.",
    "Still need help?": "Wciąż potrzebujesz pomocy?",
    "If your question is not listed here, use the contact page for a direct answer and a free quote.": "Jeśli Twojego pytania tu nie ma, skorzystaj ze strony kontaktowej po bezpośrednią odpowiedź i darmową wycenę.",
    "Project references": "Materiały projektu",
    "Domestic, commercial, end of tenancy and Airbnb cleaning for Newcastle, Gateshead, Chester-le-Street and Durham.": "Sprzątanie domowe, komercyjne, po najmie i Airbnb dla Newcastle, Gateshead, Chester-le-Street i Durham.",
    "Call / WhatsApp": "Telefon / WhatsApp",
    "Chat on WhatsApp": "Napisz na WhatsApp",
    "Call Now": "Dzwoń teraz"
  };

  if (lang === "pl") {
    const textNodes = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = textNodes.nextNode())) {
      const parent = node.parentElement;
      if (!parent || ["SCRIPT", "STYLE", "NOSCRIPT", "TEXTAREA"].includes(parent.tagName)) {
        continue;
      }
      if (parent.closest("[data-i18n]") || parent.closest("[data-i18n-placeholder]")) {
        continue;
      }
      const trimmed = (node.textContent || "").trim();
      if (!trimmed || !Object.prototype.hasOwnProperty.call(legacyPolishTextMap, trimmed)) {
        continue;
      }
      node.textContent = (node.textContent || "").replace(trimmed, legacyPolishTextMap[trimmed]);
    }

    document.querySelectorAll("[placeholder]").forEach((field) => {
      const placeholder = field.getAttribute("placeholder");
      if (placeholder && Object.prototype.hasOwnProperty.call(legacyPolishTextMap, placeholder)) {
        field.setAttribute("placeholder", legacyPolishTextMap[placeholder]);
      }
    });
  }

  const dictionary = translations[lang] || translations.en;
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[key]) {
      node.textContent = dictionary[key];
    }
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((node) => {
    const key = node.dataset.i18nPlaceholder;
    if (dictionary[key]) {
      node.setAttribute("placeholder", dictionary[key]);
    }
  });
  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("is-active", button.dataset.lang === lang);
  });
  const title = document.querySelector("title");
  if (title) {
    const attr = lang === "pl" ? "data-title-pl" : "data-title-en";
    const translatedTitle = title.getAttribute(attr);
    if (translatedTitle) {
      document.title = translatedTitle;
    }
  }
  localStorage.setItem("aga-gold-lang", lang);
}

const langButtons = document.querySelectorAll("[data-lang]");
if (langButtons.length) {
  const storedLang = localStorage.getItem("aga-gold-lang") || "en";
  applyLanguage(storedLang);
  langButtons.forEach((button) => {
    button.addEventListener("click", () => applyLanguage(button.dataset.lang));
  });
}

const quoteForm = document.querySelector("#quote-form");
if (quoteForm) {
  quoteForm.addEventListener("submit", async (event) => {
    event.preventDefault();

    const submitButton = quoteForm.querySelector('button[type="submit"]');
    const formData = new FormData(quoteForm);
    const payload = Object.fromEntries(formData.entries());
    const safeValue = (value) => (typeof value === "string" ? value.trim() : "").trim();
    const subject = `AGU Clean Services quote request: ${safeValue(payload.name) || "New enquiry"}`;
    const lines = [
      `Full name: ${safeValue(payload.name) || "Not provided"}`,
      `Phone: ${safeValue(payload.phone) || "Not provided"}`,
      `Email: ${safeValue(payload.email) || "Not provided"}`,
      `Service: ${safeValue(payload.service) || "Not provided"}`,
      `Property details: ${safeValue(payload.message) || "Not provided"}`,
      "",
      `Submitted from: ${window.location.href}`
    ];
    const mailtoUrl = `mailto:agucleanservices@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(lines.join("\n"))}`;

    if (submitButton) {
      submitButton.disabled = true;
      submitButton.dataset.originalLabel = submitButton.textContent || "Send enquiry";
      submitButton.textContent = "Sending...";
    }

    try {
      try {
        const response = await fetch("/api/contact", {
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify(payload)
        });

        if (!response.ok) {
          console.warn("Quote API unavailable, falling back to Gmail connector.");
        }
      } catch {
        console.warn("Quote API unavailable, falling back to Gmail connector.");
      }

      quoteForm.reset();
      window.location.href = mailtoUrl;
    } catch (error) {
      window.location.href = mailtoUrl;
    } finally {
      if (submitButton) {
        submitButton.disabled = false;
        submitButton.textContent = submitButton.dataset.originalLabel || "Send enquiry";
      }
    }
  });
}

const reviewForm = document.querySelector("#review-form");
if (reviewForm) {
  reviewForm.addEventListener("submit", async (event) => {
    event.preventDefault();

    const submitButton = reviewForm.querySelector('button[type="submit"]');
    const formData = new FormData(reviewForm);
    const payload = Object.fromEntries(formData.entries());
    const safeValue = (value) => (typeof value === "string" ? value.trim() : "").trim();
    const selectedRating = Math.min(Math.max(Number(payload.rating || 0), 1), 5) || 0;
    const stars = selectedRating ? `${"★".repeat(selectedRating)}${"☆".repeat(5 - selectedRating)}` : "No rating";
    const subject = `AGU Clean Services review: ${safeValue(payload.name) || "New review"}`;
    const lines = [
      `Customer: ${safeValue(payload.name) || "Not provided"}`,
      `Email: ${safeValue(payload.email) || "Not provided"}`,
      `Rating: ${stars} (${selectedRating || "Not provided"}/5)`,
      `Opinion: ${safeValue(payload.message) || "Not provided"}`,
      "",
      `Submitted from: ${window.location.href}`
    ];
    const mailtoUrl = `mailto:agucleanservices@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(lines.join("\n"))}`;

    if (submitButton) {
      submitButton.disabled = true;
      submitButton.dataset.originalLabel = submitButton.textContent || "Add review";
      submitButton.textContent = "Sending...";
    }

    try {
      try {
        const response = await fetch("/api/review", {
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            ...payload,
            kind: "review"
          })
        });

        if (!response.ok) {
          console.warn("Review API unavailable, falling back to Gmail connector.");
        }
      } catch {
        console.warn("Review API unavailable, falling back to Gmail connector.");
      }

      reviewForm.reset();
      window.location.href = mailtoUrl;
    } catch {
      window.location.href = mailtoUrl;
    } finally {
      if (submitButton) {
        submitButton.disabled = false;
        submitButton.textContent = submitButton.dataset.originalLabel || "Add review";
      }
    }
  });
}
