const navToggle = document.querySelector("[data-nav-toggle]");
const navLinks = document.querySelector("[data-nav-links]");

if (navToggle && navLinks) {
  navToggle.addEventListener("click", () => {
    const isOpen = navLinks.classList.toggle("is-open");
    navToggle.setAttribute("aria-expanded", String(isOpen));
  });

  navLinks.querySelectorAll("a").forEach((link) => {
    link.addEventListener("click", () => {
      navLinks.classList.remove("is-open");
      navToggle.setAttribute("aria-expanded", "false");
    });
  });
}

const page = document.body.dataset.page;
if (page) {
  document.querySelectorAll("[data-page-link]").forEach((link) => {
    if (link.dataset.pageLink === page) {
      link.classList.add("is-active");
    }
  });
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.aboutMe": "About Me",
    "nav.services": "Services",
    "nav.prices": "Prices",
    "nav.reviews": "Reviews",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.search": "Search website",
    "nav.call": "Call Now",
    "nav.whatsapp": "WhatsApp",
    "home.eyebrow": "Professional Home & Commercial Cleaning",
    "home.h1": "AGU Clean Services",
    "home.lead": "Newcastle, Gateshead, Chester-le-Street and Durham. Trusted home, rental and commercial cleaning with fast quotes and friendly service.",
    "home.cta1": "Get Free Quote",
    "home.cta2": "View Services",
    "home.point1": "✔ Regular & fortnightly home cleaning",
    "home.point2": "✔ Full property deep clean",
    "home.point3": "✔ Move-out ready, agent standard",
    "home.point4": "✔ Offices, shops, salons and Airbnb resets",
    "home.quick": "Quick contact",
    "home.quickText": "Free quotes are available by phone, WhatsApp or contact form.",
    "home.area1": "Main service area",
    "home.area2": "Local flexible bookings",
    "home.area3": "Domestic and tenancy jobs",
    "home.quote": "Free Quote",
    "home.quoteText": "Fast response on WhatsApp",
    "home.trust1h": "Reliable & trusted",
    "home.trust1p": "A service clients can feel confident booking",
    "home.trust2h": "Fully insured",
    "home.trust2p": "Public liability cover for added peace of mind",
    "home.trust3h": "Flexible hours",
    "home.trust3p": "Weekday, evening and tailored booking options",
    "home.trust4h": "Free quotes",
    "home.trust4p": "WhatsApp or phone quotes with no obligation",
    "home.servicesH": "Cleaning services built around real client needs",
    "home.servicesP": "Simple service categories, clear communication and flexible scheduling make the business easy to trust and easy to book.",
    "services.jumpLabel": "Jump to service:",
    "services.openPage": "Open service page",
    "services.requestQuote": "Request Quote",
    "services.openSection": "Go to service section",
    "svc.domestic.h": "Domestic cleaning",
    "svc.domestic.p": "Regular weekly or fortnightly home cleaning focused on comfort, consistency and day-to-day upkeep.",
    "svc.deep.h": "Deep cleaning",
    "svc.deep.p": "Detailed full-property cleans for kitchens, bathrooms and neglected areas that need a proper reset.",
    "svc.tenancy.h": "End of tenancy",
    "svc.tenancy.p": "Move-out cleaning prepared for lettings, property handovers and clients who need a stronger finish.",
    "svc.commercial.h": "Commercial cleaning",
    "svc.commercial.p": "Offices, salons, shops and small business spaces cleaned to stay tidy, professional and ready for clients.",
    "svc.airbnb.h": "Airbnb cleaning",
    "svc.airbnb.p": "Fast turnaround support for short-stay properties, including reset-ready presentation between guests.",
    "svc.venues.h": "After-hours venues",
    "svc.venues.p": "Cleaning support for clubs, pubs and hospitality spaces that need flexible timing outside normal hours.",
    "home.whyH": "Why clients choose AGU CLEANING SERVICES",
    "home.whyP": "The business should feel calm, trustworthy and professional. That starts with clear pricing, responsive contact and a dependable standard of work.",
    "home.why1": "✔ Fully focused on practical, client-facing cleaning services",
    "home.why2": "✔ Suitable for homes, offices, tenancy and Airbnb work",
    "home.why3": "✔ Friendly communication without corporate tone",
    "home.why4": "✔ Strong fit for local recommendations and repeat bookings",
    "home.aboutEyebrow": "About Agnieszka",
    "home.aboutH": "Friendly service with a professional standard.",
    "home.aboutP": "AGU CLEANING SERVICES is positioned as a reliable local business that values trust, punctuality and a clean finish clients can immediately feel.",
    "home.about1": "✔ Local service for Newcastle, Gateshead, Chester-le-Street and Durham",
    "home.about2": "✔ Clear communication by phone or WhatsApp",
    "home.about3": "✔ Flexible quotes based on property size and scope",
    "home.pricingH": "Simple and clear starting prices",
    "home.pricingP": "Visible starting rates help the website feel professional while still keeping quotes flexible for property size, condition and exact scope of work.",
    "price.regular.h": "Regular cleaning",
    "price.regular.p": "Weekly or fortnightly visits",
    "price.regular.d": "General home upkeep and routine cleaning.",
    "price.deep.h": "Deep cleaning",
    "price.deep.p": "Depends on property size",
    "price.deep.d": "Thorough reset for kitchens, bathrooms and full homes.",
    "price.tenancy.h": "End of tenancy",
    "price.tenancy.p": "Move-out focused finish",
    "price.tenancy.d": "Prepared for landlords, agents and property handover.",
    "price.commercial.h": "Commercial",
    "price.commercial.p": "Flexible scheduling available",
    "price.commercial.d": "Offices, salons, shops and small business spaces.",
    "home.reviewsH": "Trusted locally for reliable, friendly cleaning",
    "home.reviewsP": "Real client feedback helps new customers feel confident booking a cleaner they can trust.",
    "home.rev1": "Very professional and easy to arrange. The flat looked fresh, clean and ready straight away.",
    "home.rev2": "Reliable service and good communication. Exactly the type of cleaner you feel comfortable recommending.",
    "home.rev3": "Helpful for tenancy cleaning and completed everything to a strong standard with no fuss.",
    "home.ctaBandH": "Ready to book? Contact us today!",
    "home.ctaBandP": "Message on WhatsApp, call directly or use the quote form for a fast response.",
    "home.ctaBand1": "Go to Contact",
    "home.ctaBand2": "View Prices",
    "dashboard.panelH": "Operations Dashboard Snapshot",
    "dashboard.panelP": "A practical one-screen view showing service flow, enquiries and booking context for cleaner conversion.",
    "dashboard.panelPoint1": "✔ Live service snapshots and next action guidance",
    "dashboard.panelPoint2": "✔ Direct flow from service pages to quote requests",
    "dashboard.panelPoint3": "✔ Clean visual control for team confidence",
    "dashboard.panelVisualAlt": "Premium brand token board",
    "dashboard.panelVisualCaption": "Design token panel for a premium brand-aligned interface.",
    "dashboard.openPanel": "Open dashboard",
    "dashboard.manageServices": "View service pages",
    "dashboard.contactForm": "Go to contact form",
    "dashboard.contactPanelP": "The dashboard route keeps lead status and service context visible across the whole customer journey.",
    "dashboard.airbnbLink": "View Airbnb service",
    "dashboard.contactNow": "Need help? Contact",
    "dashboard.panelCaption": "Visual operations view for a more reliable service experience.",
    "dashboard.brandPanelP": "Brand consistency increases when every service step is connected to the operational dashboard and action path.",
    "footer.desc": "Domestic, commercial, end of tenancy and Airbnb cleaning for Newcastle, Gateshead, Chester-le-Street and Durham.",
    "footer.pages": "Pages",
    "footer.contact": "Contact",
    "footer.note": "© 2026 AGU CLEANING SERVICES. Reliable local cleaning with clear service and flexible booking.",
    "about.eyebrow": "About AGU Clean Services",
    "about.h1": "About AGU Clean Services",
    "about.lead": "Local, trusted and professional cleaning in Newcastle and beyond.",
    "about.sec1h": "Built around trust, consistency and clear communication",
    "about.sec1p": "The business plan is simple: people do not only buy cleaning. They buy peace of mind, reliability and a cleaner who does not let them down.",
    "about.list1": "✔ Local focus on Newcastle, Gateshead, Chester-le-Street and Durham",
    "about.list2": "✔ Premium presentation without cold corporate language",
    "about.list3": "✔ Clear service categories clients understand immediately",
    "about.list4": "✔ Good fit for repeat domestic clients and property contacts",
    "about.coreEye": "Core Positioning",
    "about.coreH": "Friendly professional business",
    "about.coreP": "The website, contact style and service structure are designed to look established, honest and approachable from the first visit.",
    "about.core1": "✔ Reliable and friendly service",
    "about.core2": "✔ Flexible booking and simple quoting",
    "about.core3": "✔ Strong visual brand for online ads and referrals",
    "about.oppH": "Best business opportunities",
    "about.oppP": "The strongest growth areas from the business plan are regular domestic work, end of tenancy cleaning, Airbnb resets and contact with local letting agents.",
    "about.card1h": "Repeat home clients",
    "about.card1p": "Weekly and fortnightly bookings help create consistent revenue and local word-of-mouth referrals.",
    "about.card2h": "Tenancy cleaning",
    "about.card2p": "Higher-value cleaning jobs with strong fit for agents, landlords and end-of-lease schedules.",
    "about.card3h": "Airbnb support",
    "about.card3p": "Short-stay property resets add flexibility and build useful relationships with hosts and managers.",
    "about.storyH": "A brand designed to feel calm, polished and genuinely dependable.",
    "about.storyP": "AGU Clean Services is built to feel established, local and dependable. The goal is a calm, approachable brand experience with reliable standards clients can trust every time.",
    "about.story1H": "Local and personal",
    "about.story1P": "The business is positioned for Newcastle, Gateshead, Chester-le-Street and Durham with a local identity that feels personal rather than corporate.",
    "about.story2H": "Professional standard",
    "about.story2P": "Clients still expect punctuality, polish, strong communication and an overall standard they can rely on every time.",
    "about.story3H": "Built for repeat trust",
    "about.story3P": "The aim is not just a one-off clean. It is repeat work, recommendations and a strong reputation built through consistency.",
    "about.clientsH": "Who the service is best suited for",
    "about.clientsP": "The business plan is strongest where there is clear, repeatable need: homes, rental property handovers, Airbnb hosting and smaller business premises.",
    "about.clients1": "✔ Busy households needing regular weekly or fortnightly support",
    "about.clients2": "✔ Tenants, landlords and letting agents preparing for handover",
    "about.clients3": "✔ Airbnb hosts needing quick resets between guest stays",
    "about.clients4": "✔ Offices, salons, shops and other small commercial spaces",
    "about.standardEye": "Service Standard",
    "about.standardH": "What clients should expect every time",
    "about.standardP": "A premium local cleaning brand grows through consistency. That means clear communication, respect for the property and a visible finished result every visit.",
    "about.standard1": "✔ Respect for the home, office or rental property",
    "about.standard2": "✔ Clear arrival expectations and straightforward contact",
    "about.standard3": "✔ Detail-focused cleaning with a noticeable final finish",
    "about.standard4": "✔ Flexible quotes based on size, condition and scope",
    "about.processH": "Simple process, clear communication, no unnecessary friction",
    "about.processP": "The best client experience should feel easy from first message to finished clean. That is part of what makes the business feel more professional and trustworthy.",
    "about.process1H": "1. Enquiry",
    "about.process1P": "The client sends a message by phone, WhatsApp or contact form with the property type, area and required service.",
    "about.process2H": "2. Quote",
    "about.process2P": "A clear quote is prepared based on property size, condition, frequency and the exact scope of work.",
    "about.process3H": "3. Cleaning Visit",
    "about.process3P": "The clean is completed with a respectful, careful approach and a finished result that feels fresh, polished and professionally handled.",
    "about.ctaH": "Want to see the service structure?",
    "about.ctaP": "Go to the services and prices pages for the final public-facing offer.",
    "aboutme.eyebrow": "Meet Agnieszka",
    "aboutme.h1": "Meet Agnieszka - Your Local Cleaning Professional",
    "aboutme.lead": "Agnieszka Kalina vel Kalinowska is the founder and owner of AGU Clean Services. With years of cleaning and client-service experience, she has built the business around reliability, quality and genuine care for every job.",
    "aboutme.workH": "My Work",
    "aboutme.workP": "I approach every project individually, taking time to understand each client's needs and tailoring the service so the final result matches their expectations.",
    "aboutme.workP2": "I focus on reliability, punctuality and high-quality service. I use proven products and safe cleaning methods that help keep spaces fresh and clean for longer.",
    "aboutme.expH": "Experience",
    "aboutme.expP": "Over the years, I have gained experience in both private homes and commercial environments. That experience has taught me the value of care, precision and responsibility in every stage of the job.",
    "aboutme.exp1": "Completing every stage of the job with care and precision",
    "aboutme.exp2": "Respecting each client's property and personal space",
    "aboutme.exp3": "Maintaining discretion and professionalism at all times",
    "aboutme.exp4": "Working efficiently, effectively and with full responsibility",
    "aboutme.trustH": "Reliability and Trust",
    "aboutme.trustP": "My clients value reliability, honesty, attention to detail and consistently high standards of service, combined with friendly communication and a professional approach.",
    "aboutme.trustP2": "Inviting someone into your home or business is an important decision. That is why I always work to make every professional relationship comfortable, transparent and built on mutual trust.",
    "aboutme.valuesH": "What Clients Value Most",
    "aboutme.values1": "Reliability and honesty",
    "aboutme.values2": "Attention to detail",
    "aboutme.values3": "Consistently high standards of service",
    "aboutme.values4": "Friendly communication and a professional approach",
    "aboutme.bandH": "AGU Clean Services",
    "aboutme.bandP": "Reliable Cleaning. Professional Results.",
    "aboutme.bandP2": "Home - Office - Commercial Cleaning",
    "aboutme.bandP3": "Serving Newcastle, Gateshead, Chester-le-Street and Durham.",
    "services.eyebrow": "Final Service List",
    "services.h1": "Clear services for homes, rentals and small businesses.",
    "services.lead": "The offer is structured to be easy to understand at a glance and strong enough for both private clients and property-related work.",
    "services.card1H": "Regular home cleaning",
    "services.card1P": "Weekly or fortnightly domestic cleaning for routine upkeep and a consistently fresh home.",
    "services.card2H": "Deep cleaning",
    "services.card2P": "Kitchen, bathroom and full-house detailed cleaning when a standard clean is not enough.",
    "services.card3H": "End of tenancy",
    "services.card3P": "Move-out cleaning for tenants, landlords and letting agents needing a stronger presentation standard.",
    "services.card4H": "Commercial cleaning",
    "services.card4P": "Offices, shops, salons and small premises with flexible schedules to suit the business.",
    "services.card5H": "Airbnb cleaning",
    "services.card5P": "Cleaning and reset-ready presentation between guests for short-term rental properties.",
    "services.detailH": "Detailed service pages in one clear structure",
    "services.detailP": "Each service below is written as its own offer block, so clients can quickly understand what is included, who it is best for and when to request that type of clean.",
    "services.domesticH": "Domestic Cleaning",
    "services.domesticP": "Regular domestic cleaning is ideal for clients who want a clean, comfortable home without the stress of managing everything themselves each week.",
    "services.domesticEye": "Best for",
    "services.domesticSub": "A consistently fresh and well-kept home",
    "services.domesticBody": "This service is designed for everyday upkeep, helping clients stay on top of cleanliness with a dependable recurring schedule and a polished result.",
    "services.domestic1": "✔ Weekly or fortnightly visits",
    "services.domestic2": "✔ Kitchens, bathrooms, dusting and floors",
    "services.domestic3": "✔ Best for busy households and repeat clients",
    "services.deepH": "Deep Cleaning",
    "services.deepP": "A more intensive service for properties that need a proper reset, stronger detail work and a visibly fresher finish throughout the home.",
    "services.deepEye": "Detailed clean",
    "services.deepSub": "When a standard clean is not enough",
    "services.deepBody": "Deep cleaning is suited to first visits, seasonal resets or properties that need more detailed attention in kitchens, bathrooms and neglected areas.",
    "services.deep1": "✔ Detailed attention to kitchens and bathrooms",
    "services.deep2": "✔ Suitable before events, after busy periods or first-time cleans",
    "services.deep3": "✔ Flexible scope depending on property size and condition",
    "services.tenancyH": "End of Tenancy Cleaning",
    "services.tenancyP": "This service is intended for move-out situations where a property needs to look clean, presentable and ready for handover to the next tenant, landlord or agent.",
    "services.tenancyEye": "Move-out clean",
    "services.tenancySub": "Prepared for property handover",
    "services.tenancyBody": "It is one of the most valuable services in the offer because it solves a clear need and suits both private clients and property contacts.",
    "services.tenancy1": "✔ Stronger presentation standard for handover",
    "services.tenancy2": "✔ Suitable for tenants, landlords and letting agencies",
    "services.tenancy3": "✔ Useful where a more thorough finish is required",
    "services.airbnbH": "Airbnb Cleaning",
    "services.airbnbP": "A practical short-stay property service for hosts who need reliable cleaning and a clean, welcoming setup between guests.",
    "services.airbnbEye": "Turnaround service",
    "services.airbnbSub": "Ready for the next guest",
    "services.airbnbBody": "Airbnb cleaning focuses on speed, consistency and presentation so short-stay properties stay reset-ready between bookings.",
    "services.airbnb1": "✔ Fast reset between guest stays",
    "services.airbnb2": "✔ Focus on presentation, cleanliness and consistency",
    "services.airbnb3": "✔ Ideal for hosts and property managers",
    "services.commercialH": "Commercial Cleaning",
    "services.commercialP": "Commercial cleaning is suited to offices, shops, salons and other smaller business spaces that need a clean, professional environment for staff and customers.",
    "services.commercialEye": "Business spaces",
    "services.commercialSub": "Clean, presentable and easy to maintain",
    "services.commercialBody": "This service helps local businesses maintain a more polished environment without needing a large corporate cleaning contract.",
    "services.commercial1": "✔ Offices, salons, shops and similar premises",
    "services.commercial2": "✔ Flexible scheduling around business hours",
    "services.commercial3": "✔ A reliable local option for regular upkeep",
    "services.secH": "How the service pages should feel",
    "services.secP": "This structure makes the brand look established: visible categories, practical wording and no unnecessary marketing filler.",
    "services.list1": "✔ Direct service naming",
    "services.list2": "✔ Short explanations with real use cases",
    "services.list3": "✔ Easy route from service to quote request",
    "services.flowEye": "Best conversion flow",
    "services.flowH": "Service page → price page → contact page",
    "services.flowP": "That flow suits both local domestic clients and agent or host enquiries looking for fast clarity.",
    "services.ctaH": "Need rates for one of these services?",
    "services.ctaP": "Go to the prices page for the public starting-price structure.",
    "prices.eyebrow": "Our Pricing",
    "prices.h1": "Simple starting prices with flexible quoting.",
    "prices.lead": "Public rates build trust quickly. Final quotes still depend on property size, condition, frequency and scope of work.",
    "prices.airbnbH": "Airbnb cleaning",
    "prices.airbnbP": "Starting from £45 depending on property size and turnover requirements.",
    "prices.freeH": "Free quotes available",
    "prices.freeP": "Clients can request pricing by call, WhatsApp or the contact form.",
    "prices.areaH": "Service area",
    "prices.areaP": "Newcastle, Gateshead, Chester-le-Street and Durham, with quotes adjusted to property and travel context.",
    "prices.ctaH": "Need an exact quote?",
    "prices.ctaP": "Tell us the property type, location and service needed, and we can provide a tailored price.",
    "prices.back": "Back to Services",
    "reviews.eyebrow": "Client Reviews",
    "reviews.h1": "What Our Clients Say",
    "reviews.lead": "Real reviews from real clients in Newcastle and surrounding areas.",
    "reviews.secH": "Why the reviews page matters",
    "reviews.secP": "It reinforces the most important sales message from the business plan: clients buy trust, peace of mind and someone dependable.",
    "reviews.nextEye": "Next step",
    "reviews.nextH": "Use this page to support Google and Facebook growth",
    "reviews.nextP": "Once real reviews are collected, replace placeholder copy with genuine feedback and keep the same layout.",
    "contact.eyebrow": "Contact AGU Clean Services",
    "contact.h1": "Contact AGU Clean Services",
    "contact.lead": "Get your free quote today. We usually respond within 1 to 2 hours by WhatsApp, phone or contact form.",
    "contact.callLabel": "Call / WhatsApp",
    "contact.emailLabel": "Email",
    "contact.areaLabel": "Service Area",
    "contact.ownerLabel": "Owner",
    "contact.ownerName": "Agnieszka Kalina",
    "contact.servicesValue": "Domestic • Commercial • Tenancy • Airbnb",
    "contact.areas": "Newcastle • Gateshead • Chester-le-Street • Durham",
    "contact.formH": "Request your free quote",
    "contact.formP": "Send your service type, property details and preferred contact method. We will get back to you quickly with a tailored quote.",
    "contact.name": "Full name",
    "contact.namePh": "Your name",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.select": "Select service",
    "contact.message": "Property details",
    "contact.messagePh": "Property size, location and any details that help with the quote",
    "contact.send": "Request Free Quote"
  },
  pl: {
    "nav.home": "Start",
    "nav.about": "O nas",
    "nav.aboutMe": "O mnie",
    "nav.services": "Uslugi",
    "nav.prices": "Cennik",
    "nav.reviews": "Opinie",
    "nav.faq": "FAQ",
    "nav.contact": "Kontakt",
    "nav.search": "Szukaj na stronie",
    "nav.call": "Zadzwon teraz",
    "nav.whatsapp": "WhatsApp",
    "home.eyebrow": "Lokalna, rzetelna firma sprzatajaca",
    "home.h1": "Profesjonalne sprzatanie z dopracowanym, spokojnym efektem.",
    "home.lead": "AGU CLEANING SERVICES pomaga utrzymac domy, biura i nieruchomosci na wynajem w czystosci, porzadku i gotowosci do codziennego uzytku w Newcastle, Gateshead i Durham.",
    "home.cta1": "Darmowa wycena",
    "home.cta2": "Zobacz uslugi",
    "home.point1": "✔ Sprzatanie domowe i komercyjne",
    "home.point2": "✔ Elastyczne wizyty cykliczne lub jednorazowe",
    "home.point3": "✔ Sprzatanie po najmie i obsluga Airbnb",
    "home.point4": "✔ Przyjazna i niezawodna lokalna usluga",
    "home.quick": "Szybki kontakt",
    "home.quickText": "Darmowe wyceny sa dostepne przez telefon, WhatsApp lub formularz kontaktowy.",
    "home.area1": "Glowny obszar dzialania",
    "home.area2": "Elastyczne lokalne terminy",
    "home.area3": "Zlecenia domowe i po najmie",
    "home.quote": "Darmowa wycena",
    "home.quoteText": "Szybka odpowiedz na WhatsApp",
    "home.trust1h": "Rzetelna usluga",
    "home.trust1p": "Pewnie i konsekwentnie",
    "home.trust2h": "Elastyczne godziny",
    "home.trust2p": "Opcje w tygodniu i po godzinach",
    "home.trust3h": "Dom i firma",
    "home.trust3p": "Domy, biura i wynajem",
    "home.trust4h": "Jasne wyceny",
    "home.trust4p": "Bez ukrytych kosztow",
    "home.servicesH": "Uslugi sprzatania dopasowane do realnych potrzeb klientow",
    "home.servicesP": "Proste kategorie uslug, jasna komunikacja i elastyczne terminy sprawiaja, ze firmie latwo zaufac i latwo ja zarezerwowac.",
    "svc.domestic.h": "Sprzatanie domowe",
    "svc.domestic.p": "Regularne cotygodniowe lub dwutygodniowe sprzatanie domu nastawione na komfort, powtarzalnosc i codzienny porzadek.",
    "svc.deep.h": "Gruntowne sprzatanie",
    "svc.deep.p": "Dokladne sprzatanie calej nieruchomosci, kuchni, lazienek i trudniejszych stref wymagajacych resetu.",
    "svc.tenancy.h": "Sprzatanie po najmie",
    "svc.tenancy.p": "Sprzatanie po wyprowadzce przygotowane pod przekazanie nieruchomosci i wynajem.",
    "svc.commercial.h": "Sprzatanie komercyjne",
    "svc.commercial.p": "Biura, salony, sklepy i male firmy utrzymane w czystosci i gotowe na klientow.",
    "svc.airbnb.h": "Sprzatanie Airbnb",
    "svc.airbnb.p": "Szybkie przygotowanie nieruchomosci krotkoterminowych pomiedzy pobytami gosci.",
    "svc.venues.h": "Lokale po godzinach",
    "svc.venues.p": "Wsparcie sprzatajace dla klubow, pubow i lokali wymagajacych elastycznych godzin.",
    "home.whyH": "Dlaczego klienci wybieraja AGU CLEANING SERVICES",
    "home.whyP": "Firma powinna sprawiac wrazenie spokojnej, godnej zaufania i profesjonalnej. Zaczyna sie to od jasnych cen, sprawnego kontaktu i niezawodnego standardu pracy.",
    "home.why1": "✔ Skupienie na praktycznych uslugach dla klienta",
    "home.why2": "✔ Odpowiednie dla domow, biur, najmu i Airbnb",
    "home.why3": "✔ Przyjazna komunikacja bez korporacyjnego tonu",
    "home.why4": "✔ Dobra podstawa pod polecenia i stalych klientow",
    "home.aboutEyebrow": "O Agnieszce",
    "home.aboutH": "Przyjazna usluga z profesjonalnym standardem.",
    "home.aboutP": "AGU CLEANING SERVICES to rzetelna lokalna firma, ktora stawia na zaufanie, punktualnosc i efekt czystosci odczuwalny od razu.",
    "home.about1": "✔ Lokalna usluga dla Newcastle, Gateshead i Durham",
    "home.about2": "✔ Jasna komunikacja przez telefon i WhatsApp",
    "home.about3": "✔ Elastyczne wyceny wedlug wielkosci i zakresu pracy",
    "home.pricingH": "Proste i jasne ceny startowe",
    "home.pricingP": "Widoczne ceny startowe sprawiaja, ze strona wyglada profesjonalnie, a jednoczesnie pozostawiaja elastycznosc wyceny wedlug metrazu, stanu i zakresu pracy.",
    "price.regular.h": "Sprzatanie regularne",
    "price.regular.p": "Wizyty co tydzien lub co dwa tygodnie",
    "price.regular.d": "Biezace utrzymanie domu i rutynowe sprzatanie.",
    "price.deep.h": "Gruntowne sprzatanie",
    "price.deep.p": "Zalezy od wielkosci nieruchomosci",
    "price.deep.d": "Dokladny reset kuchni, lazienek i calego domu.",
    "price.tenancy.h": "Sprzatanie po najmie",
    "price.tenancy.p": "Standard pod wyprowadzke",
    "price.tenancy.d": "Przygotowane pod wlascicieli, agentow i przekazanie lokalu.",
    "price.commercial.h": "Komercyjne",
    "price.commercial.p": "Dostepny elastyczny grafik",
    "price.commercial.d": "Biura, salony, sklepy i male firmy.",
    "home.reviewsH": "Lokalne zaufanie i przyjazna, rzetelna usluga",
    "home.reviewsP": "Opinie powinny wzmacniac to, co obiecuje marka: zaufanie, sprawny kontakt i czysty efekt bez stresu.",
    "home.rev1": "Bardzo profesjonalnie i latwo wszystko ustalic. Mieszkanie wygladalo swiezo, czysto i bylo od razu gotowe.",
    "home.rev2": "Rzetelna usluga i dobra komunikacja. Dokladnie taki typ osoby, ktora mozna spokojnie polecic dalej.",
    "home.rev3": "Bardzo pomocne przy sprzataniu po najmie i wykonane na mocnym poziomie bez problemow.",
    "home.ctaBandH": "Potrzebujesz rzetelnej osoby do sprzatania domu, biura lub wynajmu?",
    "home.ctaBandP": "Przejdz do strony kontaktowej po darmowa wycene lub napisz na WhatsApp, aby szybko otrzymac odpowiedz.",
    "home.ctaBand1": "Przejdz do kontaktu",
    "home.ctaBand2": "Zobacz ceny",
    "dashboard.panelH": "Panel operacyjny uslug",
    "dashboard.panelP": "Przejrzysty podglad jednego ekranu pokazujacy biezacy przeplyw uslug, zapytania i kontekst rezerwacji.",
    "dashboard.panelPoint1": "✔ Aktywne podsumowanie uslug i kolejny krok",
    "dashboard.panelPoint2": "✔ Bezposrednie przejscie z uslug do zapytania",
    "dashboard.panelPoint3": "✔ Przejrzysty obraz operacyjny usprawniajacy decyzje",
    "dashboard.panelVisualAlt": "Premium design token board",
    "dashboard.panelVisualCaption": "Panel tokenow designu stworzony do premium, czytelnego UX.",
    "dashboard.openPanel": "Otworz panel",
    "dashboard.manageServices": "Zobacz uslugi",
    "dashboard.contactForm": "Przejdz do formularza kontaktowego",
    "dashboard.contactPanelP": "Trasa przez dashboard utrzymuje statusy leadów i kontekst uslugi widoczne w calym procesie klienta.",
    "dashboard.airbnbLink": "Strona uslugi Airbnb",
    "dashboard.contactNow": "Potrzebujesz pomocy? Kontakt",
    "dashboard.panelCaption": "Podglad operacyjny dla stabilniejszej i bardziej zaufanej uslugi.",
    "dashboard.brandPanelP": "Spojnosc marki rośnie, gdy kazdy krok uslugi polacza sie z panelem operacyjnym i jasna sciezka dzialania.",
    "footer.desc": "Sprzatanie domowe, komercyjne, po najmie i Airbnb dla Newcastle, Gateshead i Durham.",
    "footer.pages": "Podstrony",
    "footer.contact": "Kontakt",
    "footer.note": "© 2026 AGU CLEANING SERVICES. Rzetelna lokalna usluga z jasna oferta i elastycznymi terminami.",
    "about.eyebrow": "O firmie",
    "about.h1": "Lokalna marka sprzatajaca zaprojektowana tak, by wygladac profesjonalnie i budzic zaufanie.",
    "about.lead": "AGU CLEANING SERVICES jest pozycjonowana jako rzetelna lokalna firma dla sprzatania domowego, wynajmu i malych firm, z dopracowanym i spokojnym wizerunkiem.",
    "about.sec1h": "Zbudowane wokol zaufania, powtarzalnosci i jasnej komunikacji",
    "about.sec1p": "Plan biznesowy jest prosty: ludzie nie kupuja tylko sprzatania. Kupują spokoj, niezawodnosc i osobe, ktora ich nie zawiedzie.",
    "about.list1": "✔ Lokalny fokus na Newcastle, Gateshead i Durham",
    "about.list2": "✔ Premium prezentacja bez chlodnego korporacyjnego jezyka",
    "about.list3": "✔ Jasne kategorie uslug zrozumiale od razu",
    "about.list4": "✔ Dobre dopasowanie do klientow regularnych i kontaktow property",
    "about.coreEye": "Glowne pozycjonowanie",
    "about.coreH": "Przyjazna i profesjonalna firma",
    "about.coreP": "Strona, styl kontaktu i struktura uslug sa zaprojektowane tak, aby od pierwszej wizyty wygladac uczciwie, profesjonalnie i przystepnie.",
    "about.core1": "✔ Rzetelna i przyjazna usluga",
    "about.core2": "✔ Elastyczne terminy i proste wyceny",
    "about.core3": "✔ Mocny branding do ogloszen online i polecen",
    "about.oppH": "Najlepsze mozliwosci biznesowe",
    "about.oppP": "Najmocniejsze obszary wzrostu z planu biznesowego to regularne sprzatanie domowe, sprzatanie po najmie, obsluga Airbnb i kontakt z lokalnymi agentami nieruchomosci.",
    "about.card1h": "Stali klienci domowi",
    "about.card1p": "Cotygodniowe i dwutygodniowe wizyty pomagaja budowac stabilny przychod i lokalne polecenia.",
    "about.card2h": "Sprzatanie po najmie",
    "about.card2p": "Wyzej wyceniane zlecenia dobrze dopasowane do agentow, wlascicieli i terminow zakonczenia najmu.",
    "about.card3h": "Wsparcie Airbnb",
    "about.card3p": "Reset nieruchomosci krotkoterminowych daje elastycznosc i pomaga budowac relacje z hostami i managerami.",
    "about.storyH": "Marka zaprojektowana tak, aby dawala poczucie spokoju, dopracowania i prawdziwej rzetelnosci.",
    "about.storyP": "AGU CLEANING SERVICES jest zbudowane tak, aby wygladac bardziej profesjonalnie niz typowa mala strona firmy sprzatajacej. Celem jest stworzenie wrazenia uslugi przyjaznej, lokalnej i przystepnej, ale nadal premium i godnej zaufania.",
    "about.story1H": "Lokalnie i osobiscie",
    "about.story1P": "Firma jest pozycjonowana dla Newcastle, Gateshead i Durham jako lokalna marka o bardziej osobistym charakterze niz korporacyjna konkurencja.",
    "about.story2H": "Profesjonalny standard",
    "about.story2P": "Klienci nadal oczekuja punktualnosci, dopracowanego efektu, dobrej komunikacji i poziomu, na ktorym mozna polegac za kazdym razem.",
    "about.story3H": "Budowane pod dlugie zaufanie",
    "about.story3P": "Celem nie jest tylko jednorazowe sprzatanie. Celem sa powroty klientow, polecenia i mocna reputacja budowana przez konsekwencje.",
    "about.clientsH": "Dla kogo ta usluga jest najlepsza",
    "about.clientsP": "Plan biznesowy jest najmocniejszy tam, gdzie istnieje jasna i powtarzalna potrzeba: domy, przekazania nieruchomosci po najmie, Airbnb i mniejsze lokale firmowe.",
    "about.clients1": "✔ Zabiegane domy potrzebujace regularnego wsparcia co tydzien lub co dwa tygodnie",
    "about.clients2": "✔ Najemcy, wlasciciele i agenci przygotowujacy nieruchomosc do przekazania",
    "about.clients3": "✔ Hosty Airbnb potrzebujace szybkiego resetu pomiedzy pobytami gosci",
    "about.clients4": "✔ Biura, salony, sklepy i inne mniejsze przestrzenie komercyjne",
    "about.standardEye": "Standard uslugi",
    "about.standardH": "Czego klient powinien oczekiwac za kazdym razem",
    "about.standardP": "Premium lokalna marka sprzatajaca rozwija sie przez konsekwencje. To oznacza jasny kontakt, szacunek do nieruchomosci i widoczny efekt koncowy przy kazdej wizycie.",
    "about.standard1": "✔ Szacunek do domu, biura lub nieruchomosci na wynajem",
    "about.standard2": "✔ Jasne ustalenia dotyczace przyjazdu i prosty kontakt",
    "about.standard3": "✔ Dokladne sprzatanie z widocznym efektem koncowym",
    "about.standard4": "✔ Elastyczne wyceny wedlug wielkosci, stanu i zakresu pracy",
    "about.processH": "Prosty proces, jasna komunikacja i brak zbednych utrudnien",
    "about.processP": "Najlepsze doswiadczenie klienta powinno byc latwe od pierwszej wiadomosci do zakonczonego sprzatania. To takze sprawia, ze firma wyglada bardziej profesjonalnie i budzi wieksze zaufanie.",
    "about.process1H": "1. Zapytanie",
    "about.process1P": "Klient wysyla wiadomosc przez telefon, WhatsApp lub formularz z typem nieruchomosci, lokalizacja i potrzebna usluga.",
    "about.process2H": "2. Wycena",
    "about.process2P": "Przygotowywana jest jasna wycena oparta na wielkosci nieruchomosci, stanie, czestotliwosci i dokladnym zakresie prac.",
    "about.process3H": "3. Wizyta sprzatajaca",
    "about.process3P": "Sprzatanie wykonywane jest z szacunkiem, dokladnoscia i efektem koncowym, ktory daje poczucie swiezosci, porzadku i profesjonalnego wykonania.",
    "about.ctaH": "Chcesz zobaczyc strukture oferty?",
    "about.ctaP": "Przejdz do podstron uslug i cennika, aby zobaczyc finalna publiczna oferte.",
    "aboutme.eyebrow": "O mnie - Agnieszka",
    "aboutme.h1": "Osobista usluga sprzatania oparta na zaufaniu, dokladnosci i konsekwencji.",
    "aboutme.lead": "Mam na imie Agnieszka i prowadze firme sprzatajaca stworzona z pasji do czystych, uporzadkowanych i przyjaznych przestrzeni. Przez wiele lat pracy w domach, mieszkaniach i firmach przekonalam sie, ze w dobrym sprzataniu najwazniejsze sa dbalosc o szczegoly, zaufanie i konsekwencja.",
    "aboutme.workH": "Moja praca",
    "aboutme.workP": "Do kazdego zlecenia podchodze indywidualnie, poswiecajac czas na zrozumienie potrzeb klienta i dopasowanie uslugi tak, aby efekt koncowy spelnial jego oczekiwania.",
    "aboutme.workP2": "Stawiam na rzetelnosc, punktualnosc i wysoka jakosc uslug. Korzystam ze sprawdzonych srodkow i bezpiecznych metod czyszczenia, ktore pomagaja utrzymac swiezosc i czystosc na dluzej.",
    "aboutme.expH": "Doswiadczenie",
    "aboutme.expP": "Przez lata zdobylam doswiadczenie zarowno w domach prywatnych, jak i w przestrzeniach komercyjnych. To nauczylo mnie, jak wazne sa starannosc, precyzja i odpowiedzialnosc na kazdym etapie pracy.",
    "aboutme.exp1": "Wykonywanie kazdego etapu pracy z dokladnoscia i starannoscia",
    "aboutme.exp2": "Szacunek do mienia klienta i jego prywatnej przestrzeni",
    "aboutme.exp3": "Zachowanie dyskrecji i profesjonalizmu przez caly czas",
    "aboutme.exp4": "Sprawna, skuteczna i odpowiedzialna organizacja pracy",
    "aboutme.trustH": "Rzetelnosc i zaufanie",
    "aboutme.trustP": "Moi klienci cenia mnie za rzetelnosc, uczciwosc, dbalosc o szczegoly oraz stale wysoki standard uslug, polaczony z przyjazna komunikacja i profesjonalnym podejsciem.",
    "aboutme.trustP2": "Zaproszenie kogos do domu lub firmy to wazna decyzja. Dlatego zawsze dbam o to, aby wspolpraca byla komfortowa, przejrzysta i oparta na wzajemnym zaufaniu.",
    "aboutme.valuesH": "Co klienci cenia najbardziej",
    "aboutme.values1": "Rzetelnosc i uczciwosc",
    "aboutme.values2": "Dbalosc o szczegoly",
    "aboutme.values3": "Stale wysoki standard uslug",
    "aboutme.values4": "Przyjazna komunikacje i profesjonalne podejscie",
    "aboutme.bandH": "AGA Clean Services",
    "aboutme.bandP": "Rzetelne sprzatanie. Profesjonalny efekt.",
    "aboutme.bandP2": "Dom - Biuro - Sprzatanie komercyjne",
    "aboutme.bandP3": "Obsluga Newcastle, Gateshead, Chester-le-Street i Durham.",
    "services.eyebrow": "Finalna lista uslug",
    "services.jumpLabel": "Przejdz do uslugi",
    "services.openPage": "Zobacz usluge",
    "services.requestQuote": "Popros o wycene",
    "services.openSection": "Przejdz do sekcji uslugi",
    "services.h1": "Jasne uslugi dla domow, wynajmu i malych firm.",
    "services.lead": "Oferta jest ulozona tak, aby byla czytelna na pierwszy rzut oka i mocna zarowno dla klientow prywatnych, jak i zlecen property.",
    "services.card1H": "Sprzatanie domowe",
    "services.card1P": "Cotygodniowe lub co dwutygodniowe sprzatanie domu dla biezacego utrzymania i stalego efektu swiezosci.",
    "services.card2H": "Generalne sprzatanie",
    "services.card2P": "Dokladne sprzatanie kuchni, lazienki i calego domu, gdy standardowa usluga to za malo.",
    "services.card3H": "Sprzatanie po najmie",
    "services.card3P": "Sprzatanie po wyprowadzce dla najemcow, wlascicieli i agentow potrzebujacych mocniejszego standardu prezentacji.",
    "services.card4H": "Sprzatanie komercyjne",
    "services.card4P": "Biura, sklepy, salony i male lokale z elastycznym grafikiem dopasowanym do firmy.",
    "services.card5H": "Sprzatanie Airbnb",
    "services.card5P": "Sprzatanie i przygotowanie nieruchomosci pomiedzy pobytami gosci w wynajmie krotkoterminowym.",
    "services.detailH": "Kazda usluga opisana jak osobna oferta",
    "services.detailP": "Kazdy blok ponizej dziala jak osobna podstrona uslugowa, dzieki czemu klient szybko rozumie zakres, zastosowanie i najlepszy moment na dana usluge.",
    "services.domesticH": "Sprzatanie domowe",
    "services.domesticP": "Regularne sprzatanie domowe jest idealne dla klientow, ktorzy chca utrzymac czysty i komfortowy dom bez stresu zwiazanego z robieniem wszystkiego samodzielnie.",
    "services.domesticEye": "Najlepsze dla",
    "services.domesticSub": "Domu, ktory ma byc stale swiezy i zadbany",
    "services.domesticBody": "Ta usluga jest przeznaczona do codziennego utrzymania porzadku i pomaga klientom utrzymac czystosc dzieki regularnym wizytom i dopracowanemu efektowi.",
    "services.domestic1": "✔ Wizyty co tydzien lub co dwa tygodnie",
    "services.domestic2": "✔ Kuchnie, lazienki, kurze i podlogi",
    "services.domestic3": "✔ Najlepsze dla zabieganych domow i stalych klientow",
    "services.deepH": "Generalne sprzatanie",
    "services.deepP": "Bardziej intensywna usluga dla nieruchomosci, ktore potrzebuja prawdziwego resetu, wiekszej dokladnosci i widocznie swiezszego efektu.",
    "services.deepEye": "Dokladne sprzatanie",
    "services.deepSub": "Gdy standardowe sprzatanie nie wystarcza",
    "services.deepBody": "Generalne sprzatanie sprawdza sie przy pierwszych wizytach, sezonowych resetach i nieruchomosciach wymagajacych dokladniejszej pracy w kuchni, lazience i trudniejszych strefach.",
    "services.deep1": "✔ Szczegolna uwaga na kuchnie i lazienki",
    "services.deep2": "✔ Dobre przed wydarzeniami, po intensywnych okresach lub przy pierwszym sprzataniu",
    "services.deep3": "✔ Elastyczny zakres wedlug wielkosci i stanu nieruchomosci",
    "services.tenancyH": "Sprzatanie po najmie",
    "services.tenancyP": "Ta usluga jest przeznaczona do sytuacji po wyprowadzce, kiedy nieruchomosc ma wygladac czysto, schludnie i byc gotowa do przekazania kolejnemu najemcy, wlascicielowi lub agentowi.",
    "services.tenancyEye": "Sprzatanie po wyprowadzce",
    "services.tenancySub": "Przygotowane pod przekazanie nieruchomosci",
    "services.tenancyBody": "To jedna z najwartosciowszych uslug w ofercie, bo rozwiazuje bardzo konkretny problem i dobrze pasuje zarowno do klientow prywatnych, jak i kontaktow property.",
    "services.tenancy1": "✔ Mocniejszy standard prezentacji pod przekazanie",
    "services.tenancy2": "✔ Dla najemcow, wlascicieli i agencji",
    "services.tenancy3": "✔ Dobra tam, gdzie potrzebne jest dokladniejsze wykonczenie",
    "services.airbnbH": "Sprzatanie Airbnb",
    "services.airbnbP": "Praktyczna usluga dla wynajmu krotkoterminowego dla hostow, ktorzy potrzebuja rzetelnego sprzatania i dobrze przygotowanej nieruchomosci pomiedzy pobytami.",
    "services.airbnbEye": "Usluga turnover",
    "services.airbnbSub": "Gotowe na kolejnego goscia",
    "services.airbnbBody": "Sprzatanie Airbnb skupia sie na szybkosci, powtarzalnosci i prezentacji, aby nieruchomosc byla stale gotowa pomiedzy rezerwacjami.",
    "services.airbnb1": "✔ Szybki reset pomiedzy pobytami gosci",
    "services.airbnb2": "✔ Nacisk na prezentacje, czystosc i konsekwencje",
    "services.airbnb3": "✔ Dobre dla hostow i managerow nieruchomosci",
    "services.commercialH": "Sprzatanie komercyjne",
    "services.commercialP": "Sprzatanie komercyjne sprawdza sie w biurach, sklepach, salonach i innych mniejszych przestrzeniach firmowych, ktore potrzebuja czystego i profesjonalnego otoczenia dla pracownikow i klientow.",
    "services.commercialEye": "Przestrzenie firmowe",
    "services.commercialSub": "Czysto, schludnie i latwo do utrzymania",
    "services.commercialBody": "Ta usluga pomaga lokalnym firmom utrzymac bardziej dopracowane otoczenie bez potrzeby duzego korporacyjnego kontraktu sprzatajacego.",
    "services.commercial1": "✔ Biura, salony, sklepy i podobne lokale",
    "services.commercial2": "✔ Elastyczny grafik wokol godzin pracy firmy",
    "services.commercial3": "✔ Rzetelna lokalna opcja do regularnego utrzymania",
    "services.secH": "Jak powinny wygladac podstrony uslug",
    "services.secP": "Taka struktura sprawia, ze marka wyglada na uporzadkowana: widoczne kategorie, praktyczny jezyk i brak zbednego marketingowego wypelnienia.",
    "services.list1": "✔ Bezposrednie nazwy uslug",
    "services.list2": "✔ Krotkie opisy z realnymi zastosowaniami",
    "services.list3": "✔ Latwa droga od uslugi do wyceny",
    "services.flowEye": "Najlepszy flow konwersji",
    "services.flowH": "Strona uslug → cennik → kontakt",
    "services.flowP": "Taki przeplyw dobrze pasuje do lokalnych klientow domowych oraz zapytan od agentow i hostow.",
    "services.ctaH": "Potrzebujesz cen dla jednej z tych uslug?",
    "services.ctaP": "Przejdz do cennika, aby zobaczyc publiczna strukture cen startowych.",
    "prices.eyebrow": "Jasny cennik",
    "prices.h1": "Proste ceny startowe z elastyczna wycena.",
    "prices.lead": "Publiczne stawki szybko buduja zaufanie. Koncowa wycena nadal zalezy od wielkosci nieruchomosci, stanu, czestotliwosci i zakresu pracy.",
    "prices.airbnbH": "Sprzatanie Airbnb",
    "prices.airbnbP": "Od £45 w zaleznosci od wielkosci nieruchomosci i wymagan dotyczacych turnoveru.",
    "prices.freeH": "Darmowe wyceny",
    "prices.freeP": "Klienci moga otrzymac wycene telefonicznie, przez WhatsApp lub formularz kontaktowy.",
    "prices.areaH": "Obszar dzialania",
    "prices.areaP": "Newcastle, Gateshead i Durham, z wycena dopasowana do nieruchomosci i lokalizacji.",
    "prices.ctaH": "Potrzebujesz dokladnej wyceny?",
    "prices.ctaP": "Podaj typ nieruchomosci, lokalizacje i potrzebna usluge, a przygotujemy indywidualna wycene.",
    "prices.back": "Powrot do uslug",
    "reviews.eyebrow": "Sygnaly zaufania",
    "reviews.h1": "Przyjazne opinie i lokalne zaufanie ulatwiaja wybor uslugi.",
    "reviews.lead": "Ta podstrona wspiera strategię marki: ludzie chca osoby, na ktorej mozna polegac, a nie tylko listy zadan.",
    "reviews.secH": "Dlaczego strona opinii ma znaczenie",
    "reviews.secP": "Wzmacnia najwazniejszy komunikat sprzedazowy z planu biznesowego: klienci kupuja zaufanie, spokoj i kogos niezawodnego.",
    "reviews.nextEye": "Nastepny krok",
    "reviews.nextH": "Wykorzystaj te strone do wsparcia Google i Facebook growth",
    "reviews.nextP": "Gdy pojawia sie prawdziwe opinie, zamien teksty tymczasowe na autentyczny feedback i zachowaj ten sam uklad.",
    "contact.eyebrow": "Darmowa wycena",
    "contact.h1": "Skontaktuj sie z AGU CLEANING SERVICES po jasna i przyjazna wycene.",
    "contact.lead": "Wybierz najwygodniejsza metode. Zadzwoń, napisz na WhatsApp albo wyslij formularz z typem uslugi i detalami nieruchomosci.",
    "contact.callLabel": "Telefon / WhatsApp",
    "contact.emailLabel": "Email",
    "contact.areaLabel": "Obszar dzialania",
    "contact.ownerLabel": "Wlasciciel",
    "contact.ownerName": "Agnieszka Kalina",
    "contact.servicesValue": "Domowe • Komercyjne • Po najmie • Airbnb",
    "contact.areas": "Newcastle • Gateshead • Chester-le-Street • Durham",
    "contact.formH": "Popros o darmowa wycene",
    "contact.formP": "Podaj typ nieruchomosci, lokalizacje i potrzebna usluge. Ten uklad jest gotowy pod przyszla integracje backendu.",
    "contact.name": "Imie i nazwisko",
    "contact.namePh": "Twoje imie",
    "contact.phone": "Telefon",
    "contact.email": "Email",
    "contact.select": "Wybierz usluge",
    "contact.message": "Szczegoly nieruchomosci",
    "contact.messagePh": "Wielkosc nieruchomosci, lokalizacja i wszystkie informacje pomocne do wyceny",
    "contact.send": "Wyslij zapytanie"
  }
};

function applyLanguage(lang) {
  const dictionary = translations[lang] || translations.en;
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[key]) {
      node.textContent = dictionary[key];
    }
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((node) => {
    const key = node.dataset.i18nPlaceholder;
    if (dictionary[key]) {
      node.setAttribute("placeholder", dictionary[key]);
    }
  });
  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("is-active", button.dataset.lang === lang);
  });
  const title = document.querySelector("title");
  if (title) {
    const attr = lang === "pl" ? "data-title-pl" : "data-title-en";
    const translatedTitle = title.getAttribute(attr);
    if (translatedTitle) {
      document.title = translatedTitle;
    }
  }
  localStorage.setItem("aga-gold-lang", lang);
}

const langButtons = document.querySelectorAll("[data-lang]");
if (langButtons.length) {
  const storedLang = localStorage.getItem("aga-gold-lang") || "en";
  applyLanguage(storedLang);
  langButtons.forEach((button) => {
    button.addEventListener("click", () => applyLanguage(button.dataset.lang));
  });
}

const quoteForm = document.querySelector("#quote-form");
if (quoteForm) {
  quoteForm.addEventListener("submit", async (event) => {
    event.preventDefault();

    const submitButton = quoteForm.querySelector('button[type="submit"]');
    const formData = new FormData(quoteForm);
    const payload = Object.fromEntries(formData.entries());
    const safeValue = (value) => (typeof value === "string" ? value.trim() : "").trim();
    const subject = `AGU Clean Services quote request: ${safeValue(payload.name) || "New enquiry"}`;
    const lines = [
      `Full name: ${safeValue(payload.name) || "Not provided"}`,
      `Phone: ${safeValue(payload.phone) || "Not provided"}`,
      `Email: ${safeValue(payload.email) || "Not provided"}`,
      `Service: ${safeValue(payload.service) || "Not provided"}`,
      `Property details: ${safeValue(payload.message) || "Not provided"}`,
      "",
      `Submitted from: ${window.location.href}`
    ];
    const mailtoUrl = `mailto:agucleanservices@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(lines.join("\n"))}`;

    if (submitButton) {
      submitButton.disabled = true;
      submitButton.dataset.originalLabel = submitButton.textContent || "Send enquiry";
      submitButton.textContent = "Sending...";
    }

    try {
      try {
        const response = await fetch("/api/contact", {
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify(payload)
        });

        if (!response.ok) {
          console.warn("Quote API unavailable, falling back to Gmail connector.");
        }
      } catch {
        console.warn("Quote API unavailable, falling back to Gmail connector.");
      }

      quoteForm.reset();
      window.location.href = mailtoUrl;
    } catch (error) {
      window.location.href = mailtoUrl;
    } finally {
      if (submitButton) {
        submitButton.disabled = false;
        submitButton.textContent = submitButton.dataset.originalLabel || "Send enquiry";
      }
    }
  });
}
